// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RedTip.proto

package com.gproject.common.dto.proto;

public final class RedTipDTO {
  private RedTipDTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code gsp.RedTipCode}
   */
  public enum RedTipCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Mail = 1;</code>
     *
     * <pre>
     *未知错误
     * </pre>
     */
    Mail(0, 1),
    /**
     * <code>Bag = 2;</code>
     */
    Bag(1, 2),
    ;

    /**
     * <code>Mail = 1;</code>
     *
     * <pre>
     *未知错误
     * </pre>
     */
    public static final int Mail_VALUE = 1;
    /**
     * <code>Bag = 2;</code>
     */
    public static final int Bag_VALUE = 2;


    public final int getNumber() { return value; }

    public static RedTipCode valueOf(int value) {
      switch (value) {
        case 1: return Mail;
        case 2: return Bag;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RedTipCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<RedTipCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RedTipCode>() {
            public RedTipCode findValueByNumber(int number) {
              return RedTipCode.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.gproject.common.dto.proto.RedTipDTO.getDescriptor().getEnumTypes().get(0);
    }

    private static final RedTipCode[] VALUES = values();

    public static RedTipCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private RedTipCode(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:gsp.RedTipCode)
  }

  public interface RedTipDtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .gsp.RedTipCode code = 1;
    /**
     * <code>required .gsp.RedTipCode code = 1;</code>
     */
    boolean hasCode();
    /**
     * <code>required .gsp.RedTipCode code = 1;</code>
     */
    com.gproject.common.dto.proto.RedTipDTO.RedTipCode getCode();

    // optional int32 parameLst = 2;
    /**
     * <code>optional int32 parameLst = 2;</code>
     *
     * <pre>
     *参数id列表，背包可能需要多个红点提示
     * </pre>
     */
    boolean hasParameLst();
    /**
     * <code>optional int32 parameLst = 2;</code>
     *
     * <pre>
     *参数id列表，背包可能需要多个红点提示
     * </pre>
     */
    int getParameLst();
  }
  /**
   * Protobuf type {@code gsp.RedTipDto}
   */
  public static final class RedTipDto extends
      com.google.protobuf.GeneratedMessage
      implements RedTipDtoOrBuilder {
    // Use RedTipDto.newBuilder() to construct.
    private RedTipDto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RedTipDto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RedTipDto defaultInstance;
    public static RedTipDto getDefaultInstance() {
      return defaultInstance;
    }

    public RedTipDto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RedTipDto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.gproject.common.dto.proto.RedTipDTO.RedTipCode value = com.gproject.common.dto.proto.RedTipDTO.RedTipCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                code_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              parameLst_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gproject.common.dto.proto.RedTipDTO.internal_static_gsp_RedTipDto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gproject.common.dto.proto.RedTipDTO.internal_static_gsp_RedTipDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gproject.common.dto.proto.RedTipDTO.RedTipDto.class, com.gproject.common.dto.proto.RedTipDTO.RedTipDto.Builder.class);
    }

    public static com.google.protobuf.Parser<RedTipDto> PARSER =
        new com.google.protobuf.AbstractParser<RedTipDto>() {
      public RedTipDto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RedTipDto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RedTipDto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .gsp.RedTipCode code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private com.gproject.common.dto.proto.RedTipDTO.RedTipCode code_;
    /**
     * <code>required .gsp.RedTipCode code = 1;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .gsp.RedTipCode code = 1;</code>
     */
    public com.gproject.common.dto.proto.RedTipDTO.RedTipCode getCode() {
      return code_;
    }

    // optional int32 parameLst = 2;
    public static final int PARAMELST_FIELD_NUMBER = 2;
    private int parameLst_;
    /**
     * <code>optional int32 parameLst = 2;</code>
     *
     * <pre>
     *参数id列表，背包可能需要多个红点提示
     * </pre>
     */
    public boolean hasParameLst() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 parameLst = 2;</code>
     *
     * <pre>
     *参数id列表，背包可能需要多个红点提示
     * </pre>
     */
    public int getParameLst() {
      return parameLst_;
    }

    private void initFields() {
      code_ = com.gproject.common.dto.proto.RedTipDTO.RedTipCode.Mail;
      parameLst_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, code_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, parameLst_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, code_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, parameLst_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gproject.common.dto.proto.RedTipDTO.RedTipDto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.RedTipDto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.RedTipDto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.RedTipDto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.RedTipDto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.RedTipDto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.RedTipDto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.RedTipDto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.RedTipDto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.RedTipDto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gproject.common.dto.proto.RedTipDTO.RedTipDto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gsp.RedTipDto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gproject.common.dto.proto.RedTipDTO.RedTipDtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gproject.common.dto.proto.RedTipDTO.internal_static_gsp_RedTipDto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gproject.common.dto.proto.RedTipDTO.internal_static_gsp_RedTipDto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gproject.common.dto.proto.RedTipDTO.RedTipDto.class, com.gproject.common.dto.proto.RedTipDTO.RedTipDto.Builder.class);
      }

      // Construct using com.gproject.common.dto.proto.RedTipDTO.RedTipDto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        code_ = com.gproject.common.dto.proto.RedTipDTO.RedTipCode.Mail;
        bitField0_ = (bitField0_ & ~0x00000001);
        parameLst_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gproject.common.dto.proto.RedTipDTO.internal_static_gsp_RedTipDto_descriptor;
      }

      public com.gproject.common.dto.proto.RedTipDTO.RedTipDto getDefaultInstanceForType() {
        return com.gproject.common.dto.proto.RedTipDTO.RedTipDto.getDefaultInstance();
      }

      public com.gproject.common.dto.proto.RedTipDTO.RedTipDto build() {
        com.gproject.common.dto.proto.RedTipDTO.RedTipDto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gproject.common.dto.proto.RedTipDTO.RedTipDto buildPartial() {
        com.gproject.common.dto.proto.RedTipDTO.RedTipDto result = new com.gproject.common.dto.proto.RedTipDTO.RedTipDto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.parameLst_ = parameLst_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gproject.common.dto.proto.RedTipDTO.RedTipDto) {
          return mergeFrom((com.gproject.common.dto.proto.RedTipDTO.RedTipDto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gproject.common.dto.proto.RedTipDTO.RedTipDto other) {
        if (other == com.gproject.common.dto.proto.RedTipDTO.RedTipDto.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasParameLst()) {
          setParameLst(other.getParameLst());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gproject.common.dto.proto.RedTipDTO.RedTipDto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gproject.common.dto.proto.RedTipDTO.RedTipDto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .gsp.RedTipCode code = 1;
      private com.gproject.common.dto.proto.RedTipDTO.RedTipCode code_ = com.gproject.common.dto.proto.RedTipDTO.RedTipCode.Mail;
      /**
       * <code>required .gsp.RedTipCode code = 1;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .gsp.RedTipCode code = 1;</code>
       */
      public com.gproject.common.dto.proto.RedTipDTO.RedTipCode getCode() {
        return code_;
      }
      /**
       * <code>required .gsp.RedTipCode code = 1;</code>
       */
      public Builder setCode(com.gproject.common.dto.proto.RedTipDTO.RedTipCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .gsp.RedTipCode code = 1;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = com.gproject.common.dto.proto.RedTipDTO.RedTipCode.Mail;
        onChanged();
        return this;
      }

      // optional int32 parameLst = 2;
      private int parameLst_ ;
      /**
       * <code>optional int32 parameLst = 2;</code>
       *
       * <pre>
       *参数id列表，背包可能需要多个红点提示
       * </pre>
       */
      public boolean hasParameLst() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 parameLst = 2;</code>
       *
       * <pre>
       *参数id列表，背包可能需要多个红点提示
       * </pre>
       */
      public int getParameLst() {
        return parameLst_;
      }
      /**
       * <code>optional int32 parameLst = 2;</code>
       *
       * <pre>
       *参数id列表，背包可能需要多个红点提示
       * </pre>
       */
      public Builder setParameLst(int value) {
        bitField0_ |= 0x00000002;
        parameLst_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 parameLst = 2;</code>
       *
       * <pre>
       *参数id列表，背包可能需要多个红点提示
       * </pre>
       */
      public Builder clearParameLst() {
        bitField0_ = (bitField0_ & ~0x00000002);
        parameLst_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gsp.RedTipDto)
    }

    static {
      defaultInstance = new RedTipDto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gsp.RedTipDto)
  }

  public interface S2CRedTipOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .gsp.RedTipDto data = 1;
    /**
     * <code>repeated .gsp.RedTipDto data = 1;</code>
     */
    java.util.List<com.gproject.common.dto.proto.RedTipDTO.RedTipDto> 
        getDataList();
    /**
     * <code>repeated .gsp.RedTipDto data = 1;</code>
     */
    com.gproject.common.dto.proto.RedTipDTO.RedTipDto getData(int index);
    /**
     * <code>repeated .gsp.RedTipDto data = 1;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .gsp.RedTipDto data = 1;</code>
     */
    java.util.List<? extends com.gproject.common.dto.proto.RedTipDTO.RedTipDtoOrBuilder> 
        getDataOrBuilderList();
    /**
     * <code>repeated .gsp.RedTipDto data = 1;</code>
     */
    com.gproject.common.dto.proto.RedTipDTO.RedTipDtoOrBuilder getDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code gsp.S2CRedTip}
   *
   * <pre>
   *推送红点提示======进入，服务端自动推送
   * </pre>
   */
  public static final class S2CRedTip extends
      com.google.protobuf.GeneratedMessage
      implements S2CRedTipOrBuilder {
    // Use S2CRedTip.newBuilder() to construct.
    private S2CRedTip(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private S2CRedTip(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final S2CRedTip defaultInstance;
    public static S2CRedTip getDefaultInstance() {
      return defaultInstance;
    }

    public S2CRedTip getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private S2CRedTip(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                data_ = new java.util.ArrayList<com.gproject.common.dto.proto.RedTipDTO.RedTipDto>();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.add(input.readMessage(com.gproject.common.dto.proto.RedTipDTO.RedTipDto.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gproject.common.dto.proto.RedTipDTO.internal_static_gsp_S2CRedTip_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gproject.common.dto.proto.RedTipDTO.internal_static_gsp_S2CRedTip_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gproject.common.dto.proto.RedTipDTO.S2CRedTip.class, com.gproject.common.dto.proto.RedTipDTO.S2CRedTip.Builder.class);
    }

    public static com.google.protobuf.Parser<S2CRedTip> PARSER =
        new com.google.protobuf.AbstractParser<S2CRedTip>() {
      public S2CRedTip parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2CRedTip(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<S2CRedTip> getParserForType() {
      return PARSER;
    }

    // repeated .gsp.RedTipDto data = 1;
    public static final int DATA_FIELD_NUMBER = 1;
    private java.util.List<com.gproject.common.dto.proto.RedTipDTO.RedTipDto> data_;
    /**
     * <code>repeated .gsp.RedTipDto data = 1;</code>
     */
    public java.util.List<com.gproject.common.dto.proto.RedTipDTO.RedTipDto> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .gsp.RedTipDto data = 1;</code>
     */
    public java.util.List<? extends com.gproject.common.dto.proto.RedTipDTO.RedTipDtoOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .gsp.RedTipDto data = 1;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .gsp.RedTipDto data = 1;</code>
     */
    public com.gproject.common.dto.proto.RedTipDTO.RedTipDto getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .gsp.RedTipDto data = 1;</code>
     */
    public com.gproject.common.dto.proto.RedTipDTO.RedTipDtoOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    private void initFields() {
      data_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getDataCount(); i++) {
        if (!getData(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(1, data_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, data_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gproject.common.dto.proto.RedTipDTO.S2CRedTip parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.S2CRedTip parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.S2CRedTip parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.S2CRedTip parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.S2CRedTip parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.S2CRedTip parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.S2CRedTip parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.S2CRedTip parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.S2CRedTip parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.S2CRedTip parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gproject.common.dto.proto.RedTipDTO.S2CRedTip prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gsp.S2CRedTip}
     *
     * <pre>
     *推送红点提示======进入，服务端自动推送
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gproject.common.dto.proto.RedTipDTO.S2CRedTipOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gproject.common.dto.proto.RedTipDTO.internal_static_gsp_S2CRedTip_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gproject.common.dto.proto.RedTipDTO.internal_static_gsp_S2CRedTip_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gproject.common.dto.proto.RedTipDTO.S2CRedTip.class, com.gproject.common.dto.proto.RedTipDTO.S2CRedTip.Builder.class);
      }

      // Construct using com.gproject.common.dto.proto.RedTipDTO.S2CRedTip.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dataBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gproject.common.dto.proto.RedTipDTO.internal_static_gsp_S2CRedTip_descriptor;
      }

      public com.gproject.common.dto.proto.RedTipDTO.S2CRedTip getDefaultInstanceForType() {
        return com.gproject.common.dto.proto.RedTipDTO.S2CRedTip.getDefaultInstance();
      }

      public com.gproject.common.dto.proto.RedTipDTO.S2CRedTip build() {
        com.gproject.common.dto.proto.RedTipDTO.S2CRedTip result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gproject.common.dto.proto.RedTipDTO.S2CRedTip buildPartial() {
        com.gproject.common.dto.proto.RedTipDTO.S2CRedTip result = new com.gproject.common.dto.proto.RedTipDTO.S2CRedTip(this);
        int from_bitField0_ = bitField0_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gproject.common.dto.proto.RedTipDTO.S2CRedTip) {
          return mergeFrom((com.gproject.common.dto.proto.RedTipDTO.S2CRedTip)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gproject.common.dto.proto.RedTipDTO.S2CRedTip other) {
        if (other == com.gproject.common.dto.proto.RedTipDTO.S2CRedTip.getDefaultInstance()) return this;
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getDataCount(); i++) {
          if (!getData(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gproject.common.dto.proto.RedTipDTO.S2CRedTip parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gproject.common.dto.proto.RedTipDTO.S2CRedTip) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .gsp.RedTipDto data = 1;
      private java.util.List<com.gproject.common.dto.proto.RedTipDTO.RedTipDto> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = new java.util.ArrayList<com.gproject.common.dto.proto.RedTipDTO.RedTipDto>(data_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.gproject.common.dto.proto.RedTipDTO.RedTipDto, com.gproject.common.dto.proto.RedTipDTO.RedTipDto.Builder, com.gproject.common.dto.proto.RedTipDTO.RedTipDtoOrBuilder> dataBuilder_;

      /**
       * <code>repeated .gsp.RedTipDto data = 1;</code>
       */
      public java.util.List<com.gproject.common.dto.proto.RedTipDTO.RedTipDto> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .gsp.RedTipDto data = 1;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .gsp.RedTipDto data = 1;</code>
       */
      public com.gproject.common.dto.proto.RedTipDTO.RedTipDto getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .gsp.RedTipDto data = 1;</code>
       */
      public Builder setData(
          int index, com.gproject.common.dto.proto.RedTipDTO.RedTipDto value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gsp.RedTipDto data = 1;</code>
       */
      public Builder setData(
          int index, com.gproject.common.dto.proto.RedTipDTO.RedTipDto.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gsp.RedTipDto data = 1;</code>
       */
      public Builder addData(com.gproject.common.dto.proto.RedTipDTO.RedTipDto value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .gsp.RedTipDto data = 1;</code>
       */
      public Builder addData(
          int index, com.gproject.common.dto.proto.RedTipDTO.RedTipDto value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gsp.RedTipDto data = 1;</code>
       */
      public Builder addData(
          com.gproject.common.dto.proto.RedTipDTO.RedTipDto.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gsp.RedTipDto data = 1;</code>
       */
      public Builder addData(
          int index, com.gproject.common.dto.proto.RedTipDTO.RedTipDto.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gsp.RedTipDto data = 1;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends com.gproject.common.dto.proto.RedTipDTO.RedTipDto> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          super.addAll(values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .gsp.RedTipDto data = 1;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .gsp.RedTipDto data = 1;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .gsp.RedTipDto data = 1;</code>
       */
      public com.gproject.common.dto.proto.RedTipDTO.RedTipDto.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .gsp.RedTipDto data = 1;</code>
       */
      public com.gproject.common.dto.proto.RedTipDTO.RedTipDtoOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .gsp.RedTipDto data = 1;</code>
       */
      public java.util.List<? extends com.gproject.common.dto.proto.RedTipDTO.RedTipDtoOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .gsp.RedTipDto data = 1;</code>
       */
      public com.gproject.common.dto.proto.RedTipDTO.RedTipDto.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            com.gproject.common.dto.proto.RedTipDTO.RedTipDto.getDefaultInstance());
      }
      /**
       * <code>repeated .gsp.RedTipDto data = 1;</code>
       */
      public com.gproject.common.dto.proto.RedTipDTO.RedTipDto.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, com.gproject.common.dto.proto.RedTipDTO.RedTipDto.getDefaultInstance());
      }
      /**
       * <code>repeated .gsp.RedTipDto data = 1;</code>
       */
      public java.util.List<com.gproject.common.dto.proto.RedTipDTO.RedTipDto.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.gproject.common.dto.proto.RedTipDTO.RedTipDto, com.gproject.common.dto.proto.RedTipDTO.RedTipDto.Builder, com.gproject.common.dto.proto.RedTipDTO.RedTipDtoOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.gproject.common.dto.proto.RedTipDTO.RedTipDto, com.gproject.common.dto.proto.RedTipDTO.RedTipDto.Builder, com.gproject.common.dto.proto.RedTipDTO.RedTipDtoOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:gsp.S2CRedTip)
    }

    static {
      defaultInstance = new S2CRedTip(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gsp.S2CRedTip)
  }

  public interface C2SDelRedTipOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .gsp.RedTipDto parame = 1;
    /**
     * <code>required .gsp.RedTipDto parame = 1;</code>
     */
    boolean hasParame();
    /**
     * <code>required .gsp.RedTipDto parame = 1;</code>
     */
    com.gproject.common.dto.proto.RedTipDTO.RedTipDto getParame();
    /**
     * <code>required .gsp.RedTipDto parame = 1;</code>
     */
    com.gproject.common.dto.proto.RedTipDTO.RedTipDtoOrBuilder getParameOrBuilder();
  }
  /**
   * Protobuf type {@code gsp.C2SDelRedTip}
   *
   * <pre>
   *删除红点提示
   * </pre>
   */
  public static final class C2SDelRedTip extends
      com.google.protobuf.GeneratedMessage
      implements C2SDelRedTipOrBuilder {
    // Use C2SDelRedTip.newBuilder() to construct.
    private C2SDelRedTip(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private C2SDelRedTip(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final C2SDelRedTip defaultInstance;
    public static C2SDelRedTip getDefaultInstance() {
      return defaultInstance;
    }

    public C2SDelRedTip getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private C2SDelRedTip(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.gproject.common.dto.proto.RedTipDTO.RedTipDto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = parame_.toBuilder();
              }
              parame_ = input.readMessage(com.gproject.common.dto.proto.RedTipDTO.RedTipDto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(parame_);
                parame_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gproject.common.dto.proto.RedTipDTO.internal_static_gsp_C2SDelRedTip_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gproject.common.dto.proto.RedTipDTO.internal_static_gsp_C2SDelRedTip_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip.class, com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip.Builder.class);
    }

    public static com.google.protobuf.Parser<C2SDelRedTip> PARSER =
        new com.google.protobuf.AbstractParser<C2SDelRedTip>() {
      public C2SDelRedTip parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2SDelRedTip(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<C2SDelRedTip> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .gsp.RedTipDto parame = 1;
    public static final int PARAME_FIELD_NUMBER = 1;
    private com.gproject.common.dto.proto.RedTipDTO.RedTipDto parame_;
    /**
     * <code>required .gsp.RedTipDto parame = 1;</code>
     */
    public boolean hasParame() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .gsp.RedTipDto parame = 1;</code>
     */
    public com.gproject.common.dto.proto.RedTipDTO.RedTipDto getParame() {
      return parame_;
    }
    /**
     * <code>required .gsp.RedTipDto parame = 1;</code>
     */
    public com.gproject.common.dto.proto.RedTipDTO.RedTipDtoOrBuilder getParameOrBuilder() {
      return parame_;
    }

    private void initFields() {
      parame_ = com.gproject.common.dto.proto.RedTipDTO.RedTipDto.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasParame()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getParame().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, parame_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, parame_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gsp.C2SDelRedTip}
     *
     * <pre>
     *删除红点提示
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTipOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gproject.common.dto.proto.RedTipDTO.internal_static_gsp_C2SDelRedTip_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gproject.common.dto.proto.RedTipDTO.internal_static_gsp_C2SDelRedTip_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip.class, com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip.Builder.class);
      }

      // Construct using com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getParameFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (parameBuilder_ == null) {
          parame_ = com.gproject.common.dto.proto.RedTipDTO.RedTipDto.getDefaultInstance();
        } else {
          parameBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gproject.common.dto.proto.RedTipDTO.internal_static_gsp_C2SDelRedTip_descriptor;
      }

      public com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip getDefaultInstanceForType() {
        return com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip.getDefaultInstance();
      }

      public com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip build() {
        com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip buildPartial() {
        com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip result = new com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (parameBuilder_ == null) {
          result.parame_ = parame_;
        } else {
          result.parame_ = parameBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip) {
          return mergeFrom((com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip other) {
        if (other == com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip.getDefaultInstance()) return this;
        if (other.hasParame()) {
          mergeParame(other.getParame());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasParame()) {
          
          return false;
        }
        if (!getParame().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gproject.common.dto.proto.RedTipDTO.C2SDelRedTip) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .gsp.RedTipDto parame = 1;
      private com.gproject.common.dto.proto.RedTipDTO.RedTipDto parame_ = com.gproject.common.dto.proto.RedTipDTO.RedTipDto.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.gproject.common.dto.proto.RedTipDTO.RedTipDto, com.gproject.common.dto.proto.RedTipDTO.RedTipDto.Builder, com.gproject.common.dto.proto.RedTipDTO.RedTipDtoOrBuilder> parameBuilder_;
      /**
       * <code>required .gsp.RedTipDto parame = 1;</code>
       */
      public boolean hasParame() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .gsp.RedTipDto parame = 1;</code>
       */
      public com.gproject.common.dto.proto.RedTipDTO.RedTipDto getParame() {
        if (parameBuilder_ == null) {
          return parame_;
        } else {
          return parameBuilder_.getMessage();
        }
      }
      /**
       * <code>required .gsp.RedTipDto parame = 1;</code>
       */
      public Builder setParame(com.gproject.common.dto.proto.RedTipDTO.RedTipDto value) {
        if (parameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          parame_ = value;
          onChanged();
        } else {
          parameBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .gsp.RedTipDto parame = 1;</code>
       */
      public Builder setParame(
          com.gproject.common.dto.proto.RedTipDTO.RedTipDto.Builder builderForValue) {
        if (parameBuilder_ == null) {
          parame_ = builderForValue.build();
          onChanged();
        } else {
          parameBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .gsp.RedTipDto parame = 1;</code>
       */
      public Builder mergeParame(com.gproject.common.dto.proto.RedTipDTO.RedTipDto value) {
        if (parameBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              parame_ != com.gproject.common.dto.proto.RedTipDTO.RedTipDto.getDefaultInstance()) {
            parame_ =
              com.gproject.common.dto.proto.RedTipDTO.RedTipDto.newBuilder(parame_).mergeFrom(value).buildPartial();
          } else {
            parame_ = value;
          }
          onChanged();
        } else {
          parameBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .gsp.RedTipDto parame = 1;</code>
       */
      public Builder clearParame() {
        if (parameBuilder_ == null) {
          parame_ = com.gproject.common.dto.proto.RedTipDTO.RedTipDto.getDefaultInstance();
          onChanged();
        } else {
          parameBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .gsp.RedTipDto parame = 1;</code>
       */
      public com.gproject.common.dto.proto.RedTipDTO.RedTipDto.Builder getParameBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getParameFieldBuilder().getBuilder();
      }
      /**
       * <code>required .gsp.RedTipDto parame = 1;</code>
       */
      public com.gproject.common.dto.proto.RedTipDTO.RedTipDtoOrBuilder getParameOrBuilder() {
        if (parameBuilder_ != null) {
          return parameBuilder_.getMessageOrBuilder();
        } else {
          return parame_;
        }
      }
      /**
       * <code>required .gsp.RedTipDto parame = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.gproject.common.dto.proto.RedTipDTO.RedTipDto, com.gproject.common.dto.proto.RedTipDTO.RedTipDto.Builder, com.gproject.common.dto.proto.RedTipDTO.RedTipDtoOrBuilder> 
          getParameFieldBuilder() {
        if (parameBuilder_ == null) {
          parameBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.gproject.common.dto.proto.RedTipDTO.RedTipDto, com.gproject.common.dto.proto.RedTipDTO.RedTipDto.Builder, com.gproject.common.dto.proto.RedTipDTO.RedTipDtoOrBuilder>(
                  parame_,
                  getParentForChildren(),
                  isClean());
          parame_ = null;
        }
        return parameBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:gsp.C2SDelRedTip)
    }

    static {
      defaultInstance = new C2SDelRedTip(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gsp.C2SDelRedTip)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gsp_RedTipDto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gsp_RedTipDto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gsp_S2CRedTip_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gsp_S2CRedTip_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gsp_C2SDelRedTip_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gsp_C2SDelRedTip_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014RedTip.proto\022\003gsp\"=\n\tRedTipDto\022\035\n\004code" +
      "\030\001 \002(\0162\017.gsp.RedTipCode\022\021\n\tparameLst\030\002 \001" +
      "(\005\")\n\tS2CRedTip\022\034\n\004data\030\001 \003(\0132\016.gsp.RedT" +
      "ipDto\".\n\014C2SDelRedTip\022\036\n\006parame\030\001 \002(\0132\016." +
      "gsp.RedTipDto*\037\n\nRedTipCode\022\010\n\004Mail\020\001\022\007\n" +
      "\003Bag\020\002B*\n\035com.gproject.common.dto.protoB" +
      "\tRedTipDTO"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_gsp_RedTipDto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_gsp_RedTipDto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gsp_RedTipDto_descriptor,
              new java.lang.String[] { "Code", "ParameLst", });
          internal_static_gsp_S2CRedTip_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_gsp_S2CRedTip_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gsp_S2CRedTip_descriptor,
              new java.lang.String[] { "Data", });
          internal_static_gsp_C2SDelRedTip_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_gsp_C2SDelRedTip_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gsp_C2SDelRedTip_descriptor,
              new java.lang.String[] { "Parame", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
