// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Room.proto

package com.gproject.common.dto.proto;

public final class RoomDTO {
  private RoomDTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface C2SCreateRoomOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 roomType = 1;
    /**
     * <code>required int32 roomType = 1;</code>
     */
    boolean hasRoomType();
    /**
     * <code>required int32 roomType = 1;</code>
     */
    int getRoomType();
  }
  /**
   * Protobuf type {@code gsp.C2SCreateRoom}
   *
   * <pre>
   *创建房间
   * </pre>
   */
  public static final class C2SCreateRoom extends
      com.google.protobuf.GeneratedMessage
      implements C2SCreateRoomOrBuilder {
    // Use C2SCreateRoom.newBuilder() to construct.
    private C2SCreateRoom(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private C2SCreateRoom(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final C2SCreateRoom defaultInstance;
    public static C2SCreateRoom getDefaultInstance() {
      return defaultInstance;
    }

    public C2SCreateRoom getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private C2SCreateRoom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              roomType_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gproject.common.dto.proto.RoomDTO.internal_static_gsp_C2SCreateRoom_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gproject.common.dto.proto.RoomDTO.internal_static_gsp_C2SCreateRoom_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom.class, com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom.Builder.class);
    }

    public static com.google.protobuf.Parser<C2SCreateRoom> PARSER =
        new com.google.protobuf.AbstractParser<C2SCreateRoom>() {
      public C2SCreateRoom parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2SCreateRoom(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<C2SCreateRoom> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 roomType = 1;
    public static final int ROOMTYPE_FIELD_NUMBER = 1;
    private int roomType_;
    /**
     * <code>required int32 roomType = 1;</code>
     */
    public boolean hasRoomType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 roomType = 1;</code>
     */
    public int getRoomType() {
      return roomType_;
    }

    private void initFields() {
      roomType_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRoomType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, roomType_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, roomType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gsp.C2SCreateRoom}
     *
     * <pre>
     *创建房间
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gproject.common.dto.proto.RoomDTO.C2SCreateRoomOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gproject.common.dto.proto.RoomDTO.internal_static_gsp_C2SCreateRoom_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gproject.common.dto.proto.RoomDTO.internal_static_gsp_C2SCreateRoom_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom.class, com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom.Builder.class);
      }

      // Construct using com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        roomType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gproject.common.dto.proto.RoomDTO.internal_static_gsp_C2SCreateRoom_descriptor;
      }

      public com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom getDefaultInstanceForType() {
        return com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom.getDefaultInstance();
      }

      public com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom build() {
        com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom buildPartial() {
        com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom result = new com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.roomType_ = roomType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom) {
          return mergeFrom((com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom other) {
        if (other == com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom.getDefaultInstance()) return this;
        if (other.hasRoomType()) {
          setRoomType(other.getRoomType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRoomType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gproject.common.dto.proto.RoomDTO.C2SCreateRoom) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 roomType = 1;
      private int roomType_ ;
      /**
       * <code>required int32 roomType = 1;</code>
       */
      public boolean hasRoomType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 roomType = 1;</code>
       */
      public int getRoomType() {
        return roomType_;
      }
      /**
       * <code>required int32 roomType = 1;</code>
       */
      public Builder setRoomType(int value) {
        bitField0_ |= 0x00000001;
        roomType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 roomType = 1;</code>
       */
      public Builder clearRoomType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        roomType_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gsp.C2SCreateRoom)
    }

    static {
      defaultInstance = new C2SCreateRoom(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gsp.C2SCreateRoom)
  }

  public interface S2CRoomInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code gsp.S2CRoomInfo}
   *
   * <pre>
   *房间信息
   * </pre>
   */
  public static final class S2CRoomInfo extends
      com.google.protobuf.GeneratedMessage
      implements S2CRoomInfoOrBuilder {
    // Use S2CRoomInfo.newBuilder() to construct.
    private S2CRoomInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private S2CRoomInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final S2CRoomInfo defaultInstance;
    public static S2CRoomInfo getDefaultInstance() {
      return defaultInstance;
    }

    public S2CRoomInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private S2CRoomInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gproject.common.dto.proto.RoomDTO.internal_static_gsp_S2CRoomInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gproject.common.dto.proto.RoomDTO.internal_static_gsp_S2CRoomInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo.class, com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<S2CRoomInfo> PARSER =
        new com.google.protobuf.AbstractParser<S2CRoomInfo>() {
      public S2CRoomInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2CRoomInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<S2CRoomInfo> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gsp.S2CRoomInfo}
     *
     * <pre>
     *房间信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gproject.common.dto.proto.RoomDTO.S2CRoomInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gproject.common.dto.proto.RoomDTO.internal_static_gsp_S2CRoomInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gproject.common.dto.proto.RoomDTO.internal_static_gsp_S2CRoomInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo.class, com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo.Builder.class);
      }

      // Construct using com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gproject.common.dto.proto.RoomDTO.internal_static_gsp_S2CRoomInfo_descriptor;
      }

      public com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo getDefaultInstanceForType() {
        return com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo.getDefaultInstance();
      }

      public com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo build() {
        com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo buildPartial() {
        com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo result = new com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo) {
          return mergeFrom((com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo other) {
        if (other == com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gproject.common.dto.proto.RoomDTO.S2CRoomInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gsp.S2CRoomInfo)
    }

    static {
      defaultInstance = new S2CRoomInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gsp.S2CRoomInfo)
  }

  public interface C2SExitRoomOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated bytes data = 1;
    /**
     * <code>repeated bytes data = 1;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getDataList();
    /**
     * <code>repeated bytes data = 1;</code>
     */
    int getDataCount();
    /**
     * <code>repeated bytes data = 1;</code>
     */
    com.google.protobuf.ByteString getData(int index);
  }
  /**
   * Protobuf type {@code gsp.C2SExitRoom}
   *
   * <pre>
   *离开房间
   * </pre>
   */
  public static final class C2SExitRoom extends
      com.google.protobuf.GeneratedMessage
      implements C2SExitRoomOrBuilder {
    // Use C2SExitRoom.newBuilder() to construct.
    private C2SExitRoom(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private C2SExitRoom(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final C2SExitRoom defaultInstance;
    public static C2SExitRoom getDefaultInstance() {
      return defaultInstance;
    }

    public C2SExitRoom getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private C2SExitRoom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                data_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gproject.common.dto.proto.RoomDTO.internal_static_gsp_C2SExitRoom_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gproject.common.dto.proto.RoomDTO.internal_static_gsp_C2SExitRoom_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gproject.common.dto.proto.RoomDTO.C2SExitRoom.class, com.gproject.common.dto.proto.RoomDTO.C2SExitRoom.Builder.class);
    }

    public static com.google.protobuf.Parser<C2SExitRoom> PARSER =
        new com.google.protobuf.AbstractParser<C2SExitRoom>() {
      public C2SExitRoom parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new C2SExitRoom(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<C2SExitRoom> getParserForType() {
      return PARSER;
    }

    // repeated bytes data = 1;
    public static final int DATA_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> data_;
    /**
     * <code>repeated bytes data = 1;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getDataList() {
      return data_;
    }
    /**
     * <code>repeated bytes data = 1;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated bytes data = 1;</code>
     */
    public com.google.protobuf.ByteString getData(int index) {
      return data_.get(index);
    }

    private void initFields() {
      data_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < data_.size(); i++) {
        output.writeBytes(1, data_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < data_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(data_.get(i));
        }
        size += dataSize;
        size += 1 * getDataList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gproject.common.dto.proto.RoomDTO.C2SExitRoom parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.RoomDTO.C2SExitRoom parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RoomDTO.C2SExitRoom parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.RoomDTO.C2SExitRoom parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RoomDTO.C2SExitRoom parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.RoomDTO.C2SExitRoom parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RoomDTO.C2SExitRoom parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gproject.common.dto.proto.RoomDTO.C2SExitRoom parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RoomDTO.C2SExitRoom parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.RoomDTO.C2SExitRoom parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gproject.common.dto.proto.RoomDTO.C2SExitRoom prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gsp.C2SExitRoom}
     *
     * <pre>
     *离开房间
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gproject.common.dto.proto.RoomDTO.C2SExitRoomOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gproject.common.dto.proto.RoomDTO.internal_static_gsp_C2SExitRoom_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gproject.common.dto.proto.RoomDTO.internal_static_gsp_C2SExitRoom_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gproject.common.dto.proto.RoomDTO.C2SExitRoom.class, com.gproject.common.dto.proto.RoomDTO.C2SExitRoom.Builder.class);
      }

      // Construct using com.gproject.common.dto.proto.RoomDTO.C2SExitRoom.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gproject.common.dto.proto.RoomDTO.internal_static_gsp_C2SExitRoom_descriptor;
      }

      public com.gproject.common.dto.proto.RoomDTO.C2SExitRoom getDefaultInstanceForType() {
        return com.gproject.common.dto.proto.RoomDTO.C2SExitRoom.getDefaultInstance();
      }

      public com.gproject.common.dto.proto.RoomDTO.C2SExitRoom build() {
        com.gproject.common.dto.proto.RoomDTO.C2SExitRoom result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gproject.common.dto.proto.RoomDTO.C2SExitRoom buildPartial() {
        com.gproject.common.dto.proto.RoomDTO.C2SExitRoom result = new com.gproject.common.dto.proto.RoomDTO.C2SExitRoom(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gproject.common.dto.proto.RoomDTO.C2SExitRoom) {
          return mergeFrom((com.gproject.common.dto.proto.RoomDTO.C2SExitRoom)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gproject.common.dto.proto.RoomDTO.C2SExitRoom other) {
        if (other == com.gproject.common.dto.proto.RoomDTO.C2SExitRoom.getDefaultInstance()) return this;
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gproject.common.dto.proto.RoomDTO.C2SExitRoom parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gproject.common.dto.proto.RoomDTO.C2SExitRoom) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated bytes data = 1;
      private java.util.List<com.google.protobuf.ByteString> data_ = java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = new java.util.ArrayList<com.google.protobuf.ByteString>(data_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes data = 1;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getDataList() {
        return java.util.Collections.unmodifiableList(data_);
      }
      /**
       * <code>repeated bytes data = 1;</code>
       */
      public int getDataCount() {
        return data_.size();
      }
      /**
       * <code>repeated bytes data = 1;</code>
       */
      public com.google.protobuf.ByteString getData(int index) {
        return data_.get(index);
      }
      /**
       * <code>repeated bytes data = 1;</code>
       */
      public Builder setData(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes data = 1;</code>
       */
      public Builder addData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataIsMutable();
        data_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes data = 1;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureDataIsMutable();
        super.addAll(values, data_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes data = 1;</code>
       */
      public Builder clearData() {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gsp.C2SExitRoom)
    }

    static {
      defaultInstance = new C2SExitRoom(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gsp.C2SExitRoom)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gsp_C2SCreateRoom_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gsp_C2SCreateRoom_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gsp_S2CRoomInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gsp_S2CRoomInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gsp_C2SExitRoom_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gsp_C2SExitRoom_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nRoom.proto\022\003gsp\"!\n\rC2SCreateRoom\022\020\n\010ro" +
      "omType\030\001 \002(\005\"\r\n\013S2CRoomInfo\"\033\n\013C2SExitRo" +
      "om\022\014\n\004data\030\001 \003(\014B(\n\035com.gproject.common." +
      "dto.protoB\007RoomDTO"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_gsp_C2SCreateRoom_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_gsp_C2SCreateRoom_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gsp_C2SCreateRoom_descriptor,
              new java.lang.String[] { "RoomType", });
          internal_static_gsp_S2CRoomInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_gsp_S2CRoomInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gsp_S2CRoomInfo_descriptor,
              new java.lang.String[] { });
          internal_static_gsp_C2SExitRoom_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_gsp_C2SExitRoom_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gsp_C2SExitRoom_descriptor,
              new java.lang.String[] { "Data", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
