// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RPC.proto

package com.gproject.common.dto.proto;

public final class RPCDTO {
  private RPCDTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code gsp.CommandType}
   *
   * <pre>
   *命令类型
   * </pre>
   */
  public enum CommandType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Common = 1;</code>
     *
     * <pre>
     *通用类型
     * </pre>
     */
    Common(0, 1),
    /**
     * <code>Union = 2;</code>
     *
     * <pre>
     *工会
     * </pre>
     */
    Union(1, 2),
    /**
     * <code>Match = 3;</code>
     *
     * <pre>
     *匹配
     * </pre>
     */
    Match(2, 3),
    /**
     * <code>Fight = 4;</code>
     *
     * <pre>
     *战斗
     * </pre>
     */
    Fight(3, 4),
    ;

    /**
     * <code>Common = 1;</code>
     *
     * <pre>
     *通用类型
     * </pre>
     */
    public static final int Common_VALUE = 1;
    /**
     * <code>Union = 2;</code>
     *
     * <pre>
     *工会
     * </pre>
     */
    public static final int Union_VALUE = 2;
    /**
     * <code>Match = 3;</code>
     *
     * <pre>
     *匹配
     * </pre>
     */
    public static final int Match_VALUE = 3;
    /**
     * <code>Fight = 4;</code>
     *
     * <pre>
     *战斗
     * </pre>
     */
    public static final int Fight_VALUE = 4;


    public final int getNumber() { return value; }

    public static CommandType valueOf(int value) {
      switch (value) {
        case 1: return Common;
        case 2: return Union;
        case 3: return Match;
        case 4: return Fight;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CommandType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
            public CommandType findValueByNumber(int number) {
              return CommandType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.gproject.common.dto.proto.RPCDTO.getDescriptor().getEnumTypes().get(0);
    }

    private static final CommandType[] VALUES = values();

    public static CommandType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private CommandType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:gsp.CommandType)
  }

  public interface GateSendMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 playerId = 1;
    /**
     * <code>optional int64 playerId = 1;</code>
     */
    boolean hasPlayerId();
    /**
     * <code>optional int64 playerId = 1;</code>
     */
    long getPlayerId();

    // required .gsp.CommandCode cmdCode = 2;
    /**
     * <code>required .gsp.CommandCode cmdCode = 2;</code>
     */
    boolean hasCmdCode();
    /**
     * <code>required .gsp.CommandCode cmdCode = 2;</code>
     */
    com.gproject.common.dto.proto.CommandCodeDTO.CommandCode getCmdCode();

    // optional bytes reqData = 3;
    /**
     * <code>optional bytes reqData = 3;</code>
     */
    boolean hasReqData();
    /**
     * <code>optional bytes reqData = 3;</code>
     */
    com.google.protobuf.ByteString getReqData();
  }
  /**
   * Protobuf type {@code gsp.GateSendMessage}
   *
   * <pre>
   *网关发送的数据
   * </pre>
   */
  public static final class GateSendMessage extends
      com.google.protobuf.GeneratedMessage
      implements GateSendMessageOrBuilder {
    // Use GateSendMessage.newBuilder() to construct.
    private GateSendMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GateSendMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GateSendMessage defaultInstance;
    public static GateSendMessage getDefaultInstance() {
      return defaultInstance;
    }

    public GateSendMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GateSendMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.gproject.common.dto.proto.CommandCodeDTO.CommandCode value = com.gproject.common.dto.proto.CommandCodeDTO.CommandCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                cmdCode_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              reqData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gproject.common.dto.proto.RPCDTO.internal_static_gsp_GateSendMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gproject.common.dto.proto.RPCDTO.internal_static_gsp_GateSendMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gproject.common.dto.proto.RPCDTO.GateSendMessage.class, com.gproject.common.dto.proto.RPCDTO.GateSendMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<GateSendMessage> PARSER =
        new com.google.protobuf.AbstractParser<GateSendMessage>() {
      public GateSendMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GateSendMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GateSendMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 playerId = 1;
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private long playerId_;
    /**
     * <code>optional int64 playerId = 1;</code>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 playerId = 1;</code>
     */
    public long getPlayerId() {
      return playerId_;
    }

    // required .gsp.CommandCode cmdCode = 2;
    public static final int CMDCODE_FIELD_NUMBER = 2;
    private com.gproject.common.dto.proto.CommandCodeDTO.CommandCode cmdCode_;
    /**
     * <code>required .gsp.CommandCode cmdCode = 2;</code>
     */
    public boolean hasCmdCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .gsp.CommandCode cmdCode = 2;</code>
     */
    public com.gproject.common.dto.proto.CommandCodeDTO.CommandCode getCmdCode() {
      return cmdCode_;
    }

    // optional bytes reqData = 3;
    public static final int REQDATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString reqData_;
    /**
     * <code>optional bytes reqData = 3;</code>
     */
    public boolean hasReqData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes reqData = 3;</code>
     */
    public com.google.protobuf.ByteString getReqData() {
      return reqData_;
    }

    private void initFields() {
      playerId_ = 0L;
      cmdCode_ = com.gproject.common.dto.proto.CommandCodeDTO.CommandCode.C2SLoginCode;
      reqData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCmdCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, cmdCode_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, reqData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, playerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, cmdCode_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, reqData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gproject.common.dto.proto.RPCDTO.GateSendMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.RPCDTO.GateSendMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RPCDTO.GateSendMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.RPCDTO.GateSendMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RPCDTO.GateSendMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.RPCDTO.GateSendMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RPCDTO.GateSendMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gproject.common.dto.proto.RPCDTO.GateSendMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RPCDTO.GateSendMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.RPCDTO.GateSendMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gproject.common.dto.proto.RPCDTO.GateSendMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gsp.GateSendMessage}
     *
     * <pre>
     *网关发送的数据
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gproject.common.dto.proto.RPCDTO.GateSendMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gproject.common.dto.proto.RPCDTO.internal_static_gsp_GateSendMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gproject.common.dto.proto.RPCDTO.internal_static_gsp_GateSendMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gproject.common.dto.proto.RPCDTO.GateSendMessage.class, com.gproject.common.dto.proto.RPCDTO.GateSendMessage.Builder.class);
      }

      // Construct using com.gproject.common.dto.proto.RPCDTO.GateSendMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        cmdCode_ = com.gproject.common.dto.proto.CommandCodeDTO.CommandCode.C2SLoginCode;
        bitField0_ = (bitField0_ & ~0x00000002);
        reqData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gproject.common.dto.proto.RPCDTO.internal_static_gsp_GateSendMessage_descriptor;
      }

      public com.gproject.common.dto.proto.RPCDTO.GateSendMessage getDefaultInstanceForType() {
        return com.gproject.common.dto.proto.RPCDTO.GateSendMessage.getDefaultInstance();
      }

      public com.gproject.common.dto.proto.RPCDTO.GateSendMessage build() {
        com.gproject.common.dto.proto.RPCDTO.GateSendMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gproject.common.dto.proto.RPCDTO.GateSendMessage buildPartial() {
        com.gproject.common.dto.proto.RPCDTO.GateSendMessage result = new com.gproject.common.dto.proto.RPCDTO.GateSendMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cmdCode_ = cmdCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.reqData_ = reqData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gproject.common.dto.proto.RPCDTO.GateSendMessage) {
          return mergeFrom((com.gproject.common.dto.proto.RPCDTO.GateSendMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gproject.common.dto.proto.RPCDTO.GateSendMessage other) {
        if (other == com.gproject.common.dto.proto.RPCDTO.GateSendMessage.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasCmdCode()) {
          setCmdCode(other.getCmdCode());
        }
        if (other.hasReqData()) {
          setReqData(other.getReqData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCmdCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gproject.common.dto.proto.RPCDTO.GateSendMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gproject.common.dto.proto.RPCDTO.GateSendMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 playerId = 1;
      private long playerId_ ;
      /**
       * <code>optional int64 playerId = 1;</code>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 playerId = 1;</code>
       */
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <code>optional int64 playerId = 1;</code>
       */
      public Builder setPlayerId(long value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 playerId = 1;</code>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0L;
        onChanged();
        return this;
      }

      // required .gsp.CommandCode cmdCode = 2;
      private com.gproject.common.dto.proto.CommandCodeDTO.CommandCode cmdCode_ = com.gproject.common.dto.proto.CommandCodeDTO.CommandCode.C2SLoginCode;
      /**
       * <code>required .gsp.CommandCode cmdCode = 2;</code>
       */
      public boolean hasCmdCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .gsp.CommandCode cmdCode = 2;</code>
       */
      public com.gproject.common.dto.proto.CommandCodeDTO.CommandCode getCmdCode() {
        return cmdCode_;
      }
      /**
       * <code>required .gsp.CommandCode cmdCode = 2;</code>
       */
      public Builder setCmdCode(com.gproject.common.dto.proto.CommandCodeDTO.CommandCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        cmdCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .gsp.CommandCode cmdCode = 2;</code>
       */
      public Builder clearCmdCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cmdCode_ = com.gproject.common.dto.proto.CommandCodeDTO.CommandCode.C2SLoginCode;
        onChanged();
        return this;
      }

      // optional bytes reqData = 3;
      private com.google.protobuf.ByteString reqData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes reqData = 3;</code>
       */
      public boolean hasReqData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes reqData = 3;</code>
       */
      public com.google.protobuf.ByteString getReqData() {
        return reqData_;
      }
      /**
       * <code>optional bytes reqData = 3;</code>
       */
      public Builder setReqData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        reqData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes reqData = 3;</code>
       */
      public Builder clearReqData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        reqData_ = getDefaultInstance().getReqData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gsp.GateSendMessage)
    }

    static {
      defaultInstance = new GateSendMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gsp.GateSendMessage)
  }

  public interface SendGateMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated int64 playerIds = 1;
    /**
     * <code>repeated int64 playerIds = 1;</code>
     */
    java.util.List<java.lang.Long> getPlayerIdsList();
    /**
     * <code>repeated int64 playerIds = 1;</code>
     */
    int getPlayerIdsCount();
    /**
     * <code>repeated int64 playerIds = 1;</code>
     */
    long getPlayerIds(int index);

    // required .gsp.CommandCode cmdCode = 2;
    /**
     * <code>required .gsp.CommandCode cmdCode = 2;</code>
     */
    boolean hasCmdCode();
    /**
     * <code>required .gsp.CommandCode cmdCode = 2;</code>
     */
    com.gproject.common.dto.proto.CommandCodeDTO.CommandCode getCmdCode();

    // optional bytes reqData = 3;
    /**
     * <code>optional bytes reqData = 3;</code>
     */
    boolean hasReqData();
    /**
     * <code>optional bytes reqData = 3;</code>
     */
    com.google.protobuf.ByteString getReqData();
  }
  /**
   * Protobuf type {@code gsp.SendGateMessage}
   *
   * <pre>
   *发往网关的数据
   * </pre>
   */
  public static final class SendGateMessage extends
      com.google.protobuf.GeneratedMessage
      implements SendGateMessageOrBuilder {
    // Use SendGateMessage.newBuilder() to construct.
    private SendGateMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SendGateMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SendGateMessage defaultInstance;
    public static SendGateMessage getDefaultInstance() {
      return defaultInstance;
    }

    public SendGateMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SendGateMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                playerIds_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              playerIds_.add(input.readInt64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                playerIds_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                playerIds_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.gproject.common.dto.proto.CommandCodeDTO.CommandCode value = com.gproject.common.dto.proto.CommandCodeDTO.CommandCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                cmdCode_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000002;
              reqData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          playerIds_ = java.util.Collections.unmodifiableList(playerIds_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gproject.common.dto.proto.RPCDTO.internal_static_gsp_SendGateMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gproject.common.dto.proto.RPCDTO.internal_static_gsp_SendGateMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gproject.common.dto.proto.RPCDTO.SendGateMessage.class, com.gproject.common.dto.proto.RPCDTO.SendGateMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<SendGateMessage> PARSER =
        new com.google.protobuf.AbstractParser<SendGateMessage>() {
      public SendGateMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SendGateMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SendGateMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated int64 playerIds = 1;
    public static final int PLAYERIDS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Long> playerIds_;
    /**
     * <code>repeated int64 playerIds = 1;</code>
     */
    public java.util.List<java.lang.Long>
        getPlayerIdsList() {
      return playerIds_;
    }
    /**
     * <code>repeated int64 playerIds = 1;</code>
     */
    public int getPlayerIdsCount() {
      return playerIds_.size();
    }
    /**
     * <code>repeated int64 playerIds = 1;</code>
     */
    public long getPlayerIds(int index) {
      return playerIds_.get(index);
    }

    // required .gsp.CommandCode cmdCode = 2;
    public static final int CMDCODE_FIELD_NUMBER = 2;
    private com.gproject.common.dto.proto.CommandCodeDTO.CommandCode cmdCode_;
    /**
     * <code>required .gsp.CommandCode cmdCode = 2;</code>
     */
    public boolean hasCmdCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .gsp.CommandCode cmdCode = 2;</code>
     */
    public com.gproject.common.dto.proto.CommandCodeDTO.CommandCode getCmdCode() {
      return cmdCode_;
    }

    // optional bytes reqData = 3;
    public static final int REQDATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString reqData_;
    /**
     * <code>optional bytes reqData = 3;</code>
     */
    public boolean hasReqData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes reqData = 3;</code>
     */
    public com.google.protobuf.ByteString getReqData() {
      return reqData_;
    }

    private void initFields() {
      playerIds_ = java.util.Collections.emptyList();
      cmdCode_ = com.gproject.common.dto.proto.CommandCodeDTO.CommandCode.C2SLoginCode;
      reqData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCmdCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < playerIds_.size(); i++) {
        output.writeInt64(1, playerIds_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(2, cmdCode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, reqData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < playerIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(playerIds_.get(i));
        }
        size += dataSize;
        size += 1 * getPlayerIdsList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, cmdCode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, reqData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gproject.common.dto.proto.RPCDTO.SendGateMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.RPCDTO.SendGateMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RPCDTO.SendGateMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.RPCDTO.SendGateMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RPCDTO.SendGateMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.RPCDTO.SendGateMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RPCDTO.SendGateMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gproject.common.dto.proto.RPCDTO.SendGateMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RPCDTO.SendGateMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.RPCDTO.SendGateMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gproject.common.dto.proto.RPCDTO.SendGateMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gsp.SendGateMessage}
     *
     * <pre>
     *发往网关的数据
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gproject.common.dto.proto.RPCDTO.SendGateMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gproject.common.dto.proto.RPCDTO.internal_static_gsp_SendGateMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gproject.common.dto.proto.RPCDTO.internal_static_gsp_SendGateMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gproject.common.dto.proto.RPCDTO.SendGateMessage.class, com.gproject.common.dto.proto.RPCDTO.SendGateMessage.Builder.class);
      }

      // Construct using com.gproject.common.dto.proto.RPCDTO.SendGateMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        cmdCode_ = com.gproject.common.dto.proto.CommandCodeDTO.CommandCode.C2SLoginCode;
        bitField0_ = (bitField0_ & ~0x00000002);
        reqData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gproject.common.dto.proto.RPCDTO.internal_static_gsp_SendGateMessage_descriptor;
      }

      public com.gproject.common.dto.proto.RPCDTO.SendGateMessage getDefaultInstanceForType() {
        return com.gproject.common.dto.proto.RPCDTO.SendGateMessage.getDefaultInstance();
      }

      public com.gproject.common.dto.proto.RPCDTO.SendGateMessage build() {
        com.gproject.common.dto.proto.RPCDTO.SendGateMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gproject.common.dto.proto.RPCDTO.SendGateMessage buildPartial() {
        com.gproject.common.dto.proto.RPCDTO.SendGateMessage result = new com.gproject.common.dto.proto.RPCDTO.SendGateMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          playerIds_ = java.util.Collections.unmodifiableList(playerIds_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.playerIds_ = playerIds_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cmdCode_ = cmdCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.reqData_ = reqData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gproject.common.dto.proto.RPCDTO.SendGateMessage) {
          return mergeFrom((com.gproject.common.dto.proto.RPCDTO.SendGateMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gproject.common.dto.proto.RPCDTO.SendGateMessage other) {
        if (other == com.gproject.common.dto.proto.RPCDTO.SendGateMessage.getDefaultInstance()) return this;
        if (!other.playerIds_.isEmpty()) {
          if (playerIds_.isEmpty()) {
            playerIds_ = other.playerIds_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePlayerIdsIsMutable();
            playerIds_.addAll(other.playerIds_);
          }
          onChanged();
        }
        if (other.hasCmdCode()) {
          setCmdCode(other.getCmdCode());
        }
        if (other.hasReqData()) {
          setReqData(other.getReqData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCmdCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gproject.common.dto.proto.RPCDTO.SendGateMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gproject.common.dto.proto.RPCDTO.SendGateMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated int64 playerIds = 1;
      private java.util.List<java.lang.Long> playerIds_ = java.util.Collections.emptyList();
      private void ensurePlayerIdsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          playerIds_ = new java.util.ArrayList<java.lang.Long>(playerIds_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int64 playerIds = 1;</code>
       */
      public java.util.List<java.lang.Long>
          getPlayerIdsList() {
        return java.util.Collections.unmodifiableList(playerIds_);
      }
      /**
       * <code>repeated int64 playerIds = 1;</code>
       */
      public int getPlayerIdsCount() {
        return playerIds_.size();
      }
      /**
       * <code>repeated int64 playerIds = 1;</code>
       */
      public long getPlayerIds(int index) {
        return playerIds_.get(index);
      }
      /**
       * <code>repeated int64 playerIds = 1;</code>
       */
      public Builder setPlayerIds(
          int index, long value) {
        ensurePlayerIdsIsMutable();
        playerIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 playerIds = 1;</code>
       */
      public Builder addPlayerIds(long value) {
        ensurePlayerIdsIsMutable();
        playerIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 playerIds = 1;</code>
       */
      public Builder addAllPlayerIds(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensurePlayerIdsIsMutable();
        super.addAll(values, playerIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 playerIds = 1;</code>
       */
      public Builder clearPlayerIds() {
        playerIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // required .gsp.CommandCode cmdCode = 2;
      private com.gproject.common.dto.proto.CommandCodeDTO.CommandCode cmdCode_ = com.gproject.common.dto.proto.CommandCodeDTO.CommandCode.C2SLoginCode;
      /**
       * <code>required .gsp.CommandCode cmdCode = 2;</code>
       */
      public boolean hasCmdCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .gsp.CommandCode cmdCode = 2;</code>
       */
      public com.gproject.common.dto.proto.CommandCodeDTO.CommandCode getCmdCode() {
        return cmdCode_;
      }
      /**
       * <code>required .gsp.CommandCode cmdCode = 2;</code>
       */
      public Builder setCmdCode(com.gproject.common.dto.proto.CommandCodeDTO.CommandCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        cmdCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .gsp.CommandCode cmdCode = 2;</code>
       */
      public Builder clearCmdCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cmdCode_ = com.gproject.common.dto.proto.CommandCodeDTO.CommandCode.C2SLoginCode;
        onChanged();
        return this;
      }

      // optional bytes reqData = 3;
      private com.google.protobuf.ByteString reqData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes reqData = 3;</code>
       */
      public boolean hasReqData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes reqData = 3;</code>
       */
      public com.google.protobuf.ByteString getReqData() {
        return reqData_;
      }
      /**
       * <code>optional bytes reqData = 3;</code>
       */
      public Builder setReqData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        reqData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes reqData = 3;</code>
       */
      public Builder clearReqData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        reqData_ = getDefaultInstance().getReqData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gsp.SendGateMessage)
    }

    static {
      defaultInstance = new SendGateMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gsp.SendGateMessage)
  }

  public interface GameMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .gsp.CommandCode cmdCode = 1;
    /**
     * <code>required .gsp.CommandCode cmdCode = 1;</code>
     */
    boolean hasCmdCode();
    /**
     * <code>required .gsp.CommandCode cmdCode = 1;</code>
     */
    com.gproject.common.dto.proto.CommandCodeDTO.CommandCode getCmdCode();

    // optional bytes reqData = 2;
    /**
     * <code>optional bytes reqData = 2;</code>
     */
    boolean hasReqData();
    /**
     * <code>optional bytes reqData = 2;</code>
     */
    com.google.protobuf.ByteString getReqData();

    // required .gsp.CommandType cmdType = 3;
    /**
     * <code>required .gsp.CommandType cmdType = 3;</code>
     */
    boolean hasCmdType();
    /**
     * <code>required .gsp.CommandType cmdType = 3;</code>
     */
    com.gproject.common.dto.proto.RPCDTO.CommandType getCmdType();
  }
  /**
   * Protobuf type {@code gsp.GameMessage}
   *
   * <pre>
   *游戏数据包
   * </pre>
   */
  public static final class GameMessage extends
      com.google.protobuf.GeneratedMessage
      implements GameMessageOrBuilder {
    // Use GameMessage.newBuilder() to construct.
    private GameMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GameMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GameMessage defaultInstance;
    public static GameMessage getDefaultInstance() {
      return defaultInstance;
    }

    public GameMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GameMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.gproject.common.dto.proto.CommandCodeDTO.CommandCode value = com.gproject.common.dto.proto.CommandCodeDTO.CommandCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                cmdCode_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              reqData_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.gproject.common.dto.proto.RPCDTO.CommandType value = com.gproject.common.dto.proto.RPCDTO.CommandType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                cmdType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gproject.common.dto.proto.RPCDTO.internal_static_gsp_GameMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gproject.common.dto.proto.RPCDTO.internal_static_gsp_GameMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gproject.common.dto.proto.RPCDTO.GameMessage.class, com.gproject.common.dto.proto.RPCDTO.GameMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<GameMessage> PARSER =
        new com.google.protobuf.AbstractParser<GameMessage>() {
      public GameMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GameMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .gsp.CommandCode cmdCode = 1;
    public static final int CMDCODE_FIELD_NUMBER = 1;
    private com.gproject.common.dto.proto.CommandCodeDTO.CommandCode cmdCode_;
    /**
     * <code>required .gsp.CommandCode cmdCode = 1;</code>
     */
    public boolean hasCmdCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .gsp.CommandCode cmdCode = 1;</code>
     */
    public com.gproject.common.dto.proto.CommandCodeDTO.CommandCode getCmdCode() {
      return cmdCode_;
    }

    // optional bytes reqData = 2;
    public static final int REQDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString reqData_;
    /**
     * <code>optional bytes reqData = 2;</code>
     */
    public boolean hasReqData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes reqData = 2;</code>
     */
    public com.google.protobuf.ByteString getReqData() {
      return reqData_;
    }

    // required .gsp.CommandType cmdType = 3;
    public static final int CMDTYPE_FIELD_NUMBER = 3;
    private com.gproject.common.dto.proto.RPCDTO.CommandType cmdType_;
    /**
     * <code>required .gsp.CommandType cmdType = 3;</code>
     */
    public boolean hasCmdType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .gsp.CommandType cmdType = 3;</code>
     */
    public com.gproject.common.dto.proto.RPCDTO.CommandType getCmdType() {
      return cmdType_;
    }

    private void initFields() {
      cmdCode_ = com.gproject.common.dto.proto.CommandCodeDTO.CommandCode.C2SLoginCode;
      reqData_ = com.google.protobuf.ByteString.EMPTY;
      cmdType_ = com.gproject.common.dto.proto.RPCDTO.CommandType.Common;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCmdCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCmdType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, cmdCode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, reqData_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, cmdType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, cmdCode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, reqData_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, cmdType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gproject.common.dto.proto.RPCDTO.GameMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.RPCDTO.GameMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RPCDTO.GameMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.RPCDTO.GameMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RPCDTO.GameMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.RPCDTO.GameMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RPCDTO.GameMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gproject.common.dto.proto.RPCDTO.GameMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.RPCDTO.GameMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.RPCDTO.GameMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gproject.common.dto.proto.RPCDTO.GameMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gsp.GameMessage}
     *
     * <pre>
     *游戏数据包
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gproject.common.dto.proto.RPCDTO.GameMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gproject.common.dto.proto.RPCDTO.internal_static_gsp_GameMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gproject.common.dto.proto.RPCDTO.internal_static_gsp_GameMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gproject.common.dto.proto.RPCDTO.GameMessage.class, com.gproject.common.dto.proto.RPCDTO.GameMessage.Builder.class);
      }

      // Construct using com.gproject.common.dto.proto.RPCDTO.GameMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cmdCode_ = com.gproject.common.dto.proto.CommandCodeDTO.CommandCode.C2SLoginCode;
        bitField0_ = (bitField0_ & ~0x00000001);
        reqData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        cmdType_ = com.gproject.common.dto.proto.RPCDTO.CommandType.Common;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gproject.common.dto.proto.RPCDTO.internal_static_gsp_GameMessage_descriptor;
      }

      public com.gproject.common.dto.proto.RPCDTO.GameMessage getDefaultInstanceForType() {
        return com.gproject.common.dto.proto.RPCDTO.GameMessage.getDefaultInstance();
      }

      public com.gproject.common.dto.proto.RPCDTO.GameMessage build() {
        com.gproject.common.dto.proto.RPCDTO.GameMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gproject.common.dto.proto.RPCDTO.GameMessage buildPartial() {
        com.gproject.common.dto.proto.RPCDTO.GameMessage result = new com.gproject.common.dto.proto.RPCDTO.GameMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cmdCode_ = cmdCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.reqData_ = reqData_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cmdType_ = cmdType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gproject.common.dto.proto.RPCDTO.GameMessage) {
          return mergeFrom((com.gproject.common.dto.proto.RPCDTO.GameMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gproject.common.dto.proto.RPCDTO.GameMessage other) {
        if (other == com.gproject.common.dto.proto.RPCDTO.GameMessage.getDefaultInstance()) return this;
        if (other.hasCmdCode()) {
          setCmdCode(other.getCmdCode());
        }
        if (other.hasReqData()) {
          setReqData(other.getReqData());
        }
        if (other.hasCmdType()) {
          setCmdType(other.getCmdType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCmdCode()) {
          
          return false;
        }
        if (!hasCmdType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gproject.common.dto.proto.RPCDTO.GameMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gproject.common.dto.proto.RPCDTO.GameMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .gsp.CommandCode cmdCode = 1;
      private com.gproject.common.dto.proto.CommandCodeDTO.CommandCode cmdCode_ = com.gproject.common.dto.proto.CommandCodeDTO.CommandCode.C2SLoginCode;
      /**
       * <code>required .gsp.CommandCode cmdCode = 1;</code>
       */
      public boolean hasCmdCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .gsp.CommandCode cmdCode = 1;</code>
       */
      public com.gproject.common.dto.proto.CommandCodeDTO.CommandCode getCmdCode() {
        return cmdCode_;
      }
      /**
       * <code>required .gsp.CommandCode cmdCode = 1;</code>
       */
      public Builder setCmdCode(com.gproject.common.dto.proto.CommandCodeDTO.CommandCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        cmdCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .gsp.CommandCode cmdCode = 1;</code>
       */
      public Builder clearCmdCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmdCode_ = com.gproject.common.dto.proto.CommandCodeDTO.CommandCode.C2SLoginCode;
        onChanged();
        return this;
      }

      // optional bytes reqData = 2;
      private com.google.protobuf.ByteString reqData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes reqData = 2;</code>
       */
      public boolean hasReqData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes reqData = 2;</code>
       */
      public com.google.protobuf.ByteString getReqData() {
        return reqData_;
      }
      /**
       * <code>optional bytes reqData = 2;</code>
       */
      public Builder setReqData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        reqData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes reqData = 2;</code>
       */
      public Builder clearReqData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reqData_ = getDefaultInstance().getReqData();
        onChanged();
        return this;
      }

      // required .gsp.CommandType cmdType = 3;
      private com.gproject.common.dto.proto.RPCDTO.CommandType cmdType_ = com.gproject.common.dto.proto.RPCDTO.CommandType.Common;
      /**
       * <code>required .gsp.CommandType cmdType = 3;</code>
       */
      public boolean hasCmdType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .gsp.CommandType cmdType = 3;</code>
       */
      public com.gproject.common.dto.proto.RPCDTO.CommandType getCmdType() {
        return cmdType_;
      }
      /**
       * <code>required .gsp.CommandType cmdType = 3;</code>
       */
      public Builder setCmdType(com.gproject.common.dto.proto.RPCDTO.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        cmdType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .gsp.CommandType cmdType = 3;</code>
       */
      public Builder clearCmdType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cmdType_ = com.gproject.common.dto.proto.RPCDTO.CommandType.Common;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gsp.GameMessage)
    }

    static {
      defaultInstance = new GameMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gsp.GameMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gsp_GateSendMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gsp_GateSendMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gsp_SendGateMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gsp_SendGateMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gsp_GameMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gsp_GameMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tRPC.proto\022\003gsp\032\021CommandCode.proto\"W\n\017G" +
      "ateSendMessage\022\020\n\010playerId\030\001 \001(\003\022!\n\007cmdC" +
      "ode\030\002 \002(\0162\020.gsp.CommandCode\022\017\n\007reqData\030\003" +
      " \001(\014\"X\n\017SendGateMessage\022\021\n\tplayerIds\030\001 \003" +
      "(\003\022!\n\007cmdCode\030\002 \002(\0162\020.gsp.CommandCode\022\017\n" +
      "\007reqData\030\003 \001(\014\"d\n\013GameMessage\022!\n\007cmdCode" +
      "\030\001 \002(\0162\020.gsp.CommandCode\022\017\n\007reqData\030\002 \001(" +
      "\014\022!\n\007cmdType\030\003 \002(\0162\020.gsp.CommandType*:\n\013" +
      "CommandType\022\n\n\006Common\020\001\022\t\n\005Union\020\002\022\t\n\005Ma" +
      "tch\020\003\022\t\n\005Fight\020\004B\'\n\035com.gproject.common.",
      "dto.protoB\006RPCDTO"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_gsp_GateSendMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_gsp_GateSendMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gsp_GateSendMessage_descriptor,
              new java.lang.String[] { "PlayerId", "CmdCode", "ReqData", });
          internal_static_gsp_SendGateMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_gsp_SendGateMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gsp_SendGateMessage_descriptor,
              new java.lang.String[] { "PlayerIds", "CmdCode", "ReqData", });
          internal_static_gsp_GameMessage_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_gsp_GameMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gsp_GameMessage_descriptor,
              new java.lang.String[] { "CmdCode", "ReqData", "CmdType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gproject.common.dto.proto.CommandCodeDTO.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
