// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Item.proto

package com.gproject.common.dto.proto;

public final class ItemDTO {
  private ItemDTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClientItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 itemId = 1;
    /**
     * <code>required int32 itemId = 1;</code>
     */
    boolean hasItemId();
    /**
     * <code>required int32 itemId = 1;</code>
     */
    int getItemId();

    // optional int64 addNum = 2;
    /**
     * <code>optional int64 addNum = 2;</code>
     *
     * <pre>
     *获得多少物品
     * </pre>
     */
    boolean hasAddNum();
    /**
     * <code>optional int64 addNum = 2;</code>
     *
     * <pre>
     *获得多少物品
     * </pre>
     */
    long getAddNum();

    // optional bool canShow = 3;
    /**
     * <code>optional bool canShow = 3;</code>
     *
     * <pre>
     *是否需要被玩家看到
     * </pre>
     */
    boolean hasCanShow();
    /**
     * <code>optional bool canShow = 3;</code>
     *
     * <pre>
     *是否需要被玩家看到
     * </pre>
     */
    boolean getCanShow();

    // required int64 lastNum = 4;
    /**
     * <code>required int64 lastNum = 4;</code>
     *
     * <pre>
     *最终数值
     * </pre>
     */
    boolean hasLastNum();
    /**
     * <code>required int64 lastNum = 4;</code>
     *
     * <pre>
     *最终数值
     * </pre>
     */
    long getLastNum();
  }
  /**
   * Protobuf type {@code gsp.ClientItem}
   */
  public static final class ClientItem extends
      com.google.protobuf.GeneratedMessage
      implements ClientItemOrBuilder {
    // Use ClientItem.newBuilder() to construct.
    private ClientItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClientItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClientItem defaultInstance;
    public static ClientItem getDefaultInstance() {
      return defaultInstance;
    }

    public ClientItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClientItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              itemId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              addNum_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              canShow_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              lastNum_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gproject.common.dto.proto.ItemDTO.internal_static_gsp_ClientItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gproject.common.dto.proto.ItemDTO.internal_static_gsp_ClientItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gproject.common.dto.proto.ItemDTO.ClientItem.class, com.gproject.common.dto.proto.ItemDTO.ClientItem.Builder.class);
    }

    public static com.google.protobuf.Parser<ClientItem> PARSER =
        new com.google.protobuf.AbstractParser<ClientItem>() {
      public ClientItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClientItem> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 itemId = 1;
    public static final int ITEMID_FIELD_NUMBER = 1;
    private int itemId_;
    /**
     * <code>required int32 itemId = 1;</code>
     */
    public boolean hasItemId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 itemId = 1;</code>
     */
    public int getItemId() {
      return itemId_;
    }

    // optional int64 addNum = 2;
    public static final int ADDNUM_FIELD_NUMBER = 2;
    private long addNum_;
    /**
     * <code>optional int64 addNum = 2;</code>
     *
     * <pre>
     *获得多少物品
     * </pre>
     */
    public boolean hasAddNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 addNum = 2;</code>
     *
     * <pre>
     *获得多少物品
     * </pre>
     */
    public long getAddNum() {
      return addNum_;
    }

    // optional bool canShow = 3;
    public static final int CANSHOW_FIELD_NUMBER = 3;
    private boolean canShow_;
    /**
     * <code>optional bool canShow = 3;</code>
     *
     * <pre>
     *是否需要被玩家看到
     * </pre>
     */
    public boolean hasCanShow() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool canShow = 3;</code>
     *
     * <pre>
     *是否需要被玩家看到
     * </pre>
     */
    public boolean getCanShow() {
      return canShow_;
    }

    // required int64 lastNum = 4;
    public static final int LASTNUM_FIELD_NUMBER = 4;
    private long lastNum_;
    /**
     * <code>required int64 lastNum = 4;</code>
     *
     * <pre>
     *最终数值
     * </pre>
     */
    public boolean hasLastNum() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 lastNum = 4;</code>
     *
     * <pre>
     *最终数值
     * </pre>
     */
    public long getLastNum() {
      return lastNum_;
    }

    private void initFields() {
      itemId_ = 0;
      addNum_ = 0L;
      canShow_ = false;
      lastNum_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasItemId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, itemId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, addNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, canShow_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, lastNum_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, itemId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, addNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, canShow_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, lastNum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gproject.common.dto.proto.ItemDTO.ClientItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.ItemDTO.ClientItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.ItemDTO.ClientItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.ItemDTO.ClientItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.ItemDTO.ClientItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.ItemDTO.ClientItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.ItemDTO.ClientItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gproject.common.dto.proto.ItemDTO.ClientItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.ItemDTO.ClientItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.ItemDTO.ClientItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gproject.common.dto.proto.ItemDTO.ClientItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gsp.ClientItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gproject.common.dto.proto.ItemDTO.ClientItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gproject.common.dto.proto.ItemDTO.internal_static_gsp_ClientItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gproject.common.dto.proto.ItemDTO.internal_static_gsp_ClientItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gproject.common.dto.proto.ItemDTO.ClientItem.class, com.gproject.common.dto.proto.ItemDTO.ClientItem.Builder.class);
      }

      // Construct using com.gproject.common.dto.proto.ItemDTO.ClientItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        itemId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        addNum_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        canShow_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        lastNum_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gproject.common.dto.proto.ItemDTO.internal_static_gsp_ClientItem_descriptor;
      }

      public com.gproject.common.dto.proto.ItemDTO.ClientItem getDefaultInstanceForType() {
        return com.gproject.common.dto.proto.ItemDTO.ClientItem.getDefaultInstance();
      }

      public com.gproject.common.dto.proto.ItemDTO.ClientItem build() {
        com.gproject.common.dto.proto.ItemDTO.ClientItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gproject.common.dto.proto.ItemDTO.ClientItem buildPartial() {
        com.gproject.common.dto.proto.ItemDTO.ClientItem result = new com.gproject.common.dto.proto.ItemDTO.ClientItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.itemId_ = itemId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.addNum_ = addNum_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.canShow_ = canShow_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lastNum_ = lastNum_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gproject.common.dto.proto.ItemDTO.ClientItem) {
          return mergeFrom((com.gproject.common.dto.proto.ItemDTO.ClientItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gproject.common.dto.proto.ItemDTO.ClientItem other) {
        if (other == com.gproject.common.dto.proto.ItemDTO.ClientItem.getDefaultInstance()) return this;
        if (other.hasItemId()) {
          setItemId(other.getItemId());
        }
        if (other.hasAddNum()) {
          setAddNum(other.getAddNum());
        }
        if (other.hasCanShow()) {
          setCanShow(other.getCanShow());
        }
        if (other.hasLastNum()) {
          setLastNum(other.getLastNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasItemId()) {
          
          return false;
        }
        if (!hasLastNum()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gproject.common.dto.proto.ItemDTO.ClientItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gproject.common.dto.proto.ItemDTO.ClientItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 itemId = 1;
      private int itemId_ ;
      /**
       * <code>required int32 itemId = 1;</code>
       */
      public boolean hasItemId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 itemId = 1;</code>
       */
      public int getItemId() {
        return itemId_;
      }
      /**
       * <code>required int32 itemId = 1;</code>
       */
      public Builder setItemId(int value) {
        bitField0_ |= 0x00000001;
        itemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 itemId = 1;</code>
       */
      public Builder clearItemId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        itemId_ = 0;
        onChanged();
        return this;
      }

      // optional int64 addNum = 2;
      private long addNum_ ;
      /**
       * <code>optional int64 addNum = 2;</code>
       *
       * <pre>
       *获得多少物品
       * </pre>
       */
      public boolean hasAddNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 addNum = 2;</code>
       *
       * <pre>
       *获得多少物品
       * </pre>
       */
      public long getAddNum() {
        return addNum_;
      }
      /**
       * <code>optional int64 addNum = 2;</code>
       *
       * <pre>
       *获得多少物品
       * </pre>
       */
      public Builder setAddNum(long value) {
        bitField0_ |= 0x00000002;
        addNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 addNum = 2;</code>
       *
       * <pre>
       *获得多少物品
       * </pre>
       */
      public Builder clearAddNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        addNum_ = 0L;
        onChanged();
        return this;
      }

      // optional bool canShow = 3;
      private boolean canShow_ ;
      /**
       * <code>optional bool canShow = 3;</code>
       *
       * <pre>
       *是否需要被玩家看到
       * </pre>
       */
      public boolean hasCanShow() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool canShow = 3;</code>
       *
       * <pre>
       *是否需要被玩家看到
       * </pre>
       */
      public boolean getCanShow() {
        return canShow_;
      }
      /**
       * <code>optional bool canShow = 3;</code>
       *
       * <pre>
       *是否需要被玩家看到
       * </pre>
       */
      public Builder setCanShow(boolean value) {
        bitField0_ |= 0x00000004;
        canShow_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool canShow = 3;</code>
       *
       * <pre>
       *是否需要被玩家看到
       * </pre>
       */
      public Builder clearCanShow() {
        bitField0_ = (bitField0_ & ~0x00000004);
        canShow_ = false;
        onChanged();
        return this;
      }

      // required int64 lastNum = 4;
      private long lastNum_ ;
      /**
       * <code>required int64 lastNum = 4;</code>
       *
       * <pre>
       *最终数值
       * </pre>
       */
      public boolean hasLastNum() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 lastNum = 4;</code>
       *
       * <pre>
       *最终数值
       * </pre>
       */
      public long getLastNum() {
        return lastNum_;
      }
      /**
       * <code>required int64 lastNum = 4;</code>
       *
       * <pre>
       *最终数值
       * </pre>
       */
      public Builder setLastNum(long value) {
        bitField0_ |= 0x00000008;
        lastNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 lastNum = 4;</code>
       *
       * <pre>
       *最终数值
       * </pre>
       */
      public Builder clearLastNum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lastNum_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gsp.ClientItem)
    }

    static {
      defaultInstance = new ClientItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gsp.ClientItem)
  }

  public interface S2CAddItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .gsp.ClientItem data = 1;
    /**
     * <code>repeated .gsp.ClientItem data = 1;</code>
     */
    java.util.List<com.gproject.common.dto.proto.ItemDTO.ClientItem> 
        getDataList();
    /**
     * <code>repeated .gsp.ClientItem data = 1;</code>
     */
    com.gproject.common.dto.proto.ItemDTO.ClientItem getData(int index);
    /**
     * <code>repeated .gsp.ClientItem data = 1;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .gsp.ClientItem data = 1;</code>
     */
    java.util.List<? extends com.gproject.common.dto.proto.ItemDTO.ClientItemOrBuilder> 
        getDataOrBuilderList();
    /**
     * <code>repeated .gsp.ClientItem data = 1;</code>
     */
    com.gproject.common.dto.proto.ItemDTO.ClientItemOrBuilder getDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code gsp.S2CAddItem}
   *
   * <pre>
   *专用用于展示获得物品
   * </pre>
   */
  public static final class S2CAddItem extends
      com.google.protobuf.GeneratedMessage
      implements S2CAddItemOrBuilder {
    // Use S2CAddItem.newBuilder() to construct.
    private S2CAddItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private S2CAddItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final S2CAddItem defaultInstance;
    public static S2CAddItem getDefaultInstance() {
      return defaultInstance;
    }

    public S2CAddItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private S2CAddItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                data_ = new java.util.ArrayList<com.gproject.common.dto.proto.ItemDTO.ClientItem>();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.add(input.readMessage(com.gproject.common.dto.proto.ItemDTO.ClientItem.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gproject.common.dto.proto.ItemDTO.internal_static_gsp_S2CAddItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gproject.common.dto.proto.ItemDTO.internal_static_gsp_S2CAddItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gproject.common.dto.proto.ItemDTO.S2CAddItem.class, com.gproject.common.dto.proto.ItemDTO.S2CAddItem.Builder.class);
    }

    public static com.google.protobuf.Parser<S2CAddItem> PARSER =
        new com.google.protobuf.AbstractParser<S2CAddItem>() {
      public S2CAddItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2CAddItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<S2CAddItem> getParserForType() {
      return PARSER;
    }

    // repeated .gsp.ClientItem data = 1;
    public static final int DATA_FIELD_NUMBER = 1;
    private java.util.List<com.gproject.common.dto.proto.ItemDTO.ClientItem> data_;
    /**
     * <code>repeated .gsp.ClientItem data = 1;</code>
     */
    public java.util.List<com.gproject.common.dto.proto.ItemDTO.ClientItem> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .gsp.ClientItem data = 1;</code>
     */
    public java.util.List<? extends com.gproject.common.dto.proto.ItemDTO.ClientItemOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .gsp.ClientItem data = 1;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .gsp.ClientItem data = 1;</code>
     */
    public com.gproject.common.dto.proto.ItemDTO.ClientItem getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .gsp.ClientItem data = 1;</code>
     */
    public com.gproject.common.dto.proto.ItemDTO.ClientItemOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    private void initFields() {
      data_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getDataCount(); i++) {
        if (!getData(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(1, data_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, data_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gproject.common.dto.proto.ItemDTO.S2CAddItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.ItemDTO.S2CAddItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.ItemDTO.S2CAddItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.ItemDTO.S2CAddItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.ItemDTO.S2CAddItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.ItemDTO.S2CAddItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.ItemDTO.S2CAddItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gproject.common.dto.proto.ItemDTO.S2CAddItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.ItemDTO.S2CAddItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.ItemDTO.S2CAddItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gproject.common.dto.proto.ItemDTO.S2CAddItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gsp.S2CAddItem}
     *
     * <pre>
     *专用用于展示获得物品
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gproject.common.dto.proto.ItemDTO.S2CAddItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gproject.common.dto.proto.ItemDTO.internal_static_gsp_S2CAddItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gproject.common.dto.proto.ItemDTO.internal_static_gsp_S2CAddItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gproject.common.dto.proto.ItemDTO.S2CAddItem.class, com.gproject.common.dto.proto.ItemDTO.S2CAddItem.Builder.class);
      }

      // Construct using com.gproject.common.dto.proto.ItemDTO.S2CAddItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dataBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gproject.common.dto.proto.ItemDTO.internal_static_gsp_S2CAddItem_descriptor;
      }

      public com.gproject.common.dto.proto.ItemDTO.S2CAddItem getDefaultInstanceForType() {
        return com.gproject.common.dto.proto.ItemDTO.S2CAddItem.getDefaultInstance();
      }

      public com.gproject.common.dto.proto.ItemDTO.S2CAddItem build() {
        com.gproject.common.dto.proto.ItemDTO.S2CAddItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gproject.common.dto.proto.ItemDTO.S2CAddItem buildPartial() {
        com.gproject.common.dto.proto.ItemDTO.S2CAddItem result = new com.gproject.common.dto.proto.ItemDTO.S2CAddItem(this);
        int from_bitField0_ = bitField0_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gproject.common.dto.proto.ItemDTO.S2CAddItem) {
          return mergeFrom((com.gproject.common.dto.proto.ItemDTO.S2CAddItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gproject.common.dto.proto.ItemDTO.S2CAddItem other) {
        if (other == com.gproject.common.dto.proto.ItemDTO.S2CAddItem.getDefaultInstance()) return this;
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getDataCount(); i++) {
          if (!getData(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gproject.common.dto.proto.ItemDTO.S2CAddItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gproject.common.dto.proto.ItemDTO.S2CAddItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .gsp.ClientItem data = 1;
      private java.util.List<com.gproject.common.dto.proto.ItemDTO.ClientItem> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = new java.util.ArrayList<com.gproject.common.dto.proto.ItemDTO.ClientItem>(data_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.gproject.common.dto.proto.ItemDTO.ClientItem, com.gproject.common.dto.proto.ItemDTO.ClientItem.Builder, com.gproject.common.dto.proto.ItemDTO.ClientItemOrBuilder> dataBuilder_;

      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public java.util.List<com.gproject.common.dto.proto.ItemDTO.ClientItem> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public com.gproject.common.dto.proto.ItemDTO.ClientItem getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public Builder setData(
          int index, com.gproject.common.dto.proto.ItemDTO.ClientItem value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public Builder setData(
          int index, com.gproject.common.dto.proto.ItemDTO.ClientItem.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public Builder addData(com.gproject.common.dto.proto.ItemDTO.ClientItem value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public Builder addData(
          int index, com.gproject.common.dto.proto.ItemDTO.ClientItem value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public Builder addData(
          com.gproject.common.dto.proto.ItemDTO.ClientItem.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public Builder addData(
          int index, com.gproject.common.dto.proto.ItemDTO.ClientItem.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends com.gproject.common.dto.proto.ItemDTO.ClientItem> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          super.addAll(values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public com.gproject.common.dto.proto.ItemDTO.ClientItem.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public com.gproject.common.dto.proto.ItemDTO.ClientItemOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public java.util.List<? extends com.gproject.common.dto.proto.ItemDTO.ClientItemOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public com.gproject.common.dto.proto.ItemDTO.ClientItem.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            com.gproject.common.dto.proto.ItemDTO.ClientItem.getDefaultInstance());
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public com.gproject.common.dto.proto.ItemDTO.ClientItem.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, com.gproject.common.dto.proto.ItemDTO.ClientItem.getDefaultInstance());
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public java.util.List<com.gproject.common.dto.proto.ItemDTO.ClientItem.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.gproject.common.dto.proto.ItemDTO.ClientItem, com.gproject.common.dto.proto.ItemDTO.ClientItem.Builder, com.gproject.common.dto.proto.ItemDTO.ClientItemOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.gproject.common.dto.proto.ItemDTO.ClientItem, com.gproject.common.dto.proto.ItemDTO.ClientItem.Builder, com.gproject.common.dto.proto.ItemDTO.ClientItemOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:gsp.S2CAddItem)
    }

    static {
      defaultInstance = new S2CAddItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gsp.S2CAddItem)
  }

  public interface S2CSynItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .gsp.ClientItem data = 1;
    /**
     * <code>repeated .gsp.ClientItem data = 1;</code>
     */
    java.util.List<com.gproject.common.dto.proto.ItemDTO.ClientItem> 
        getDataList();
    /**
     * <code>repeated .gsp.ClientItem data = 1;</code>
     */
    com.gproject.common.dto.proto.ItemDTO.ClientItem getData(int index);
    /**
     * <code>repeated .gsp.ClientItem data = 1;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .gsp.ClientItem data = 1;</code>
     */
    java.util.List<? extends com.gproject.common.dto.proto.ItemDTO.ClientItemOrBuilder> 
        getDataOrBuilderList();
    /**
     * <code>repeated .gsp.ClientItem data = 1;</code>
     */
    com.gproject.common.dto.proto.ItemDTO.ClientItemOrBuilder getDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code gsp.S2CSynItem}
   *
   * <pre>
   *同步物品最新数值，多用于消耗物品
   * </pre>
   */
  public static final class S2CSynItem extends
      com.google.protobuf.GeneratedMessage
      implements S2CSynItemOrBuilder {
    // Use S2CSynItem.newBuilder() to construct.
    private S2CSynItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private S2CSynItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final S2CSynItem defaultInstance;
    public static S2CSynItem getDefaultInstance() {
      return defaultInstance;
    }

    public S2CSynItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private S2CSynItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                data_ = new java.util.ArrayList<com.gproject.common.dto.proto.ItemDTO.ClientItem>();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.add(input.readMessage(com.gproject.common.dto.proto.ItemDTO.ClientItem.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gproject.common.dto.proto.ItemDTO.internal_static_gsp_S2CSynItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gproject.common.dto.proto.ItemDTO.internal_static_gsp_S2CSynItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gproject.common.dto.proto.ItemDTO.S2CSynItem.class, com.gproject.common.dto.proto.ItemDTO.S2CSynItem.Builder.class);
    }

    public static com.google.protobuf.Parser<S2CSynItem> PARSER =
        new com.google.protobuf.AbstractParser<S2CSynItem>() {
      public S2CSynItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2CSynItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<S2CSynItem> getParserForType() {
      return PARSER;
    }

    // repeated .gsp.ClientItem data = 1;
    public static final int DATA_FIELD_NUMBER = 1;
    private java.util.List<com.gproject.common.dto.proto.ItemDTO.ClientItem> data_;
    /**
     * <code>repeated .gsp.ClientItem data = 1;</code>
     */
    public java.util.List<com.gproject.common.dto.proto.ItemDTO.ClientItem> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .gsp.ClientItem data = 1;</code>
     */
    public java.util.List<? extends com.gproject.common.dto.proto.ItemDTO.ClientItemOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .gsp.ClientItem data = 1;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .gsp.ClientItem data = 1;</code>
     */
    public com.gproject.common.dto.proto.ItemDTO.ClientItem getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .gsp.ClientItem data = 1;</code>
     */
    public com.gproject.common.dto.proto.ItemDTO.ClientItemOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    private void initFields() {
      data_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getDataCount(); i++) {
        if (!getData(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(1, data_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, data_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gproject.common.dto.proto.ItemDTO.S2CSynItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.ItemDTO.S2CSynItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.ItemDTO.S2CSynItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.ItemDTO.S2CSynItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.ItemDTO.S2CSynItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.ItemDTO.S2CSynItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.ItemDTO.S2CSynItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gproject.common.dto.proto.ItemDTO.S2CSynItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.ItemDTO.S2CSynItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.ItemDTO.S2CSynItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gproject.common.dto.proto.ItemDTO.S2CSynItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gsp.S2CSynItem}
     *
     * <pre>
     *同步物品最新数值，多用于消耗物品
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gproject.common.dto.proto.ItemDTO.S2CSynItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gproject.common.dto.proto.ItemDTO.internal_static_gsp_S2CSynItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gproject.common.dto.proto.ItemDTO.internal_static_gsp_S2CSynItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gproject.common.dto.proto.ItemDTO.S2CSynItem.class, com.gproject.common.dto.proto.ItemDTO.S2CSynItem.Builder.class);
      }

      // Construct using com.gproject.common.dto.proto.ItemDTO.S2CSynItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dataBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gproject.common.dto.proto.ItemDTO.internal_static_gsp_S2CSynItem_descriptor;
      }

      public com.gproject.common.dto.proto.ItemDTO.S2CSynItem getDefaultInstanceForType() {
        return com.gproject.common.dto.proto.ItemDTO.S2CSynItem.getDefaultInstance();
      }

      public com.gproject.common.dto.proto.ItemDTO.S2CSynItem build() {
        com.gproject.common.dto.proto.ItemDTO.S2CSynItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gproject.common.dto.proto.ItemDTO.S2CSynItem buildPartial() {
        com.gproject.common.dto.proto.ItemDTO.S2CSynItem result = new com.gproject.common.dto.proto.ItemDTO.S2CSynItem(this);
        int from_bitField0_ = bitField0_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gproject.common.dto.proto.ItemDTO.S2CSynItem) {
          return mergeFrom((com.gproject.common.dto.proto.ItemDTO.S2CSynItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gproject.common.dto.proto.ItemDTO.S2CSynItem other) {
        if (other == com.gproject.common.dto.proto.ItemDTO.S2CSynItem.getDefaultInstance()) return this;
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getDataCount(); i++) {
          if (!getData(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gproject.common.dto.proto.ItemDTO.S2CSynItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gproject.common.dto.proto.ItemDTO.S2CSynItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .gsp.ClientItem data = 1;
      private java.util.List<com.gproject.common.dto.proto.ItemDTO.ClientItem> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = new java.util.ArrayList<com.gproject.common.dto.proto.ItemDTO.ClientItem>(data_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.gproject.common.dto.proto.ItemDTO.ClientItem, com.gproject.common.dto.proto.ItemDTO.ClientItem.Builder, com.gproject.common.dto.proto.ItemDTO.ClientItemOrBuilder> dataBuilder_;

      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public java.util.List<com.gproject.common.dto.proto.ItemDTO.ClientItem> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public com.gproject.common.dto.proto.ItemDTO.ClientItem getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public Builder setData(
          int index, com.gproject.common.dto.proto.ItemDTO.ClientItem value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public Builder setData(
          int index, com.gproject.common.dto.proto.ItemDTO.ClientItem.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public Builder addData(com.gproject.common.dto.proto.ItemDTO.ClientItem value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public Builder addData(
          int index, com.gproject.common.dto.proto.ItemDTO.ClientItem value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public Builder addData(
          com.gproject.common.dto.proto.ItemDTO.ClientItem.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public Builder addData(
          int index, com.gproject.common.dto.proto.ItemDTO.ClientItem.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends com.gproject.common.dto.proto.ItemDTO.ClientItem> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          super.addAll(values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public com.gproject.common.dto.proto.ItemDTO.ClientItem.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public com.gproject.common.dto.proto.ItemDTO.ClientItemOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public java.util.List<? extends com.gproject.common.dto.proto.ItemDTO.ClientItemOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public com.gproject.common.dto.proto.ItemDTO.ClientItem.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            com.gproject.common.dto.proto.ItemDTO.ClientItem.getDefaultInstance());
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public com.gproject.common.dto.proto.ItemDTO.ClientItem.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, com.gproject.common.dto.proto.ItemDTO.ClientItem.getDefaultInstance());
      }
      /**
       * <code>repeated .gsp.ClientItem data = 1;</code>
       */
      public java.util.List<com.gproject.common.dto.proto.ItemDTO.ClientItem.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.gproject.common.dto.proto.ItemDTO.ClientItem, com.gproject.common.dto.proto.ItemDTO.ClientItem.Builder, com.gproject.common.dto.proto.ItemDTO.ClientItemOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.gproject.common.dto.proto.ItemDTO.ClientItem, com.gproject.common.dto.proto.ItemDTO.ClientItem.Builder, com.gproject.common.dto.proto.ItemDTO.ClientItemOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:gsp.S2CSynItem)
    }

    static {
      defaultInstance = new S2CSynItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gsp.S2CSynItem)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gsp_ClientItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gsp_ClientItem_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gsp_S2CAddItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gsp_S2CAddItem_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gsp_S2CSynItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gsp_S2CSynItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nItem.proto\022\003gsp\"N\n\nClientItem\022\016\n\006itemI" +
      "d\030\001 \002(\005\022\016\n\006addNum\030\002 \001(\003\022\017\n\007canShow\030\003 \001(\010" +
      "\022\017\n\007lastNum\030\004 \002(\003\"+\n\nS2CAddItem\022\035\n\004data\030" +
      "\001 \003(\0132\017.gsp.ClientItem\"+\n\nS2CSynItem\022\035\n\004" +
      "data\030\001 \003(\0132\017.gsp.ClientItemB(\n\035com.gproj" +
      "ect.common.dto.protoB\007ItemDTO"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_gsp_ClientItem_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_gsp_ClientItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gsp_ClientItem_descriptor,
              new java.lang.String[] { "ItemId", "AddNum", "CanShow", "LastNum", });
          internal_static_gsp_S2CAddItem_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_gsp_S2CAddItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gsp_S2CAddItem_descriptor,
              new java.lang.String[] { "Data", });
          internal_static_gsp_S2CSynItem_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_gsp_S2CSynItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gsp_S2CSynItem_descriptor,
              new java.lang.String[] { "Data", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
