// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tip.proto

package com.gproject.common.dto.proto;

public final class TipDTO {
  private TipDTO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code gsp.TipCode}
   */
  public enum TipCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UnKown = 1;</code>
     *
     * <pre>
     *未知错误
     * </pre>
     */
    UnKown(0, 1),
    /**
     * <code>Fail = 2;</code>
     */
    Fail(1, 2),
    /**
     * <code>PlayerInFighting = 3;</code>
     *
     * <pre>
     *战斗正在发生，不可以在别的设备登录
     * </pre>
     */
    PlayerInFighting(2, 3),
    /**
     * <code>TokenExpire = 4;</code>
     *
     * <pre>
     *token失效
     * </pre>
     */
    TokenExpire(3, 4),
    /**
     * <code>Uid_NULL = 5;</code>
     */
    Uid_NULL(4, 5),
    /**
     * <code>Token_NULL = 6;</code>
     */
    Token_NULL(5, 6),
    /**
     * <code>Random_NULL = 7;</code>
     */
    Random_NULL(6, 7),
    /**
     * <code>Max_bag_num = 8;</code>
     *
     * <pre>
     *最大背包数
     * </pre>
     */
    Max_bag_num(7, 8),
    /**
     * <code>Max_Item_num = 9;</code>
     *
     * <pre>
     *道具数量超出最大数
     * </pre>
     */
    Max_Item_num(8, 9),
    ;

    /**
     * <code>UnKown = 1;</code>
     *
     * <pre>
     *未知错误
     * </pre>
     */
    public static final int UnKown_VALUE = 1;
    /**
     * <code>Fail = 2;</code>
     */
    public static final int Fail_VALUE = 2;
    /**
     * <code>PlayerInFighting = 3;</code>
     *
     * <pre>
     *战斗正在发生，不可以在别的设备登录
     * </pre>
     */
    public static final int PlayerInFighting_VALUE = 3;
    /**
     * <code>TokenExpire = 4;</code>
     *
     * <pre>
     *token失效
     * </pre>
     */
    public static final int TokenExpire_VALUE = 4;
    /**
     * <code>Uid_NULL = 5;</code>
     */
    public static final int Uid_NULL_VALUE = 5;
    /**
     * <code>Token_NULL = 6;</code>
     */
    public static final int Token_NULL_VALUE = 6;
    /**
     * <code>Random_NULL = 7;</code>
     */
    public static final int Random_NULL_VALUE = 7;
    /**
     * <code>Max_bag_num = 8;</code>
     *
     * <pre>
     *最大背包数
     * </pre>
     */
    public static final int Max_bag_num_VALUE = 8;
    /**
     * <code>Max_Item_num = 9;</code>
     *
     * <pre>
     *道具数量超出最大数
     * </pre>
     */
    public static final int Max_Item_num_VALUE = 9;


    public final int getNumber() { return value; }

    public static TipCode valueOf(int value) {
      switch (value) {
        case 1: return UnKown;
        case 2: return Fail;
        case 3: return PlayerInFighting;
        case 4: return TokenExpire;
        case 5: return Uid_NULL;
        case 6: return Token_NULL;
        case 7: return Random_NULL;
        case 8: return Max_bag_num;
        case 9: return Max_Item_num;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TipCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TipCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TipCode>() {
            public TipCode findValueByNumber(int number) {
              return TipCode.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.gproject.common.dto.proto.TipDTO.getDescriptor().getEnumTypes().get(0);
    }

    private static final TipCode[] VALUES = values();

    public static TipCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TipCode(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:gsp.TipCode)
  }

  public interface GameTipOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .gsp.TipCode code = 1;
    /**
     * <code>optional .gsp.TipCode code = 1;</code>
     */
    boolean hasCode();
    /**
     * <code>optional .gsp.TipCode code = 1;</code>
     */
    com.gproject.common.dto.proto.TipDTO.TipCode getCode();

    // optional string msg = 2;
    /**
     * <code>optional string msg = 2;</code>
     */
    boolean hasMsg();
    /**
     * <code>optional string msg = 2;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code gsp.GameTip}
   */
  public static final class GameTip extends
      com.google.protobuf.GeneratedMessage
      implements GameTipOrBuilder {
    // Use GameTip.newBuilder() to construct.
    private GameTip(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GameTip(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GameTip defaultInstance;
    public static GameTip getDefaultInstance() {
      return defaultInstance;
    }

    public GameTip getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GameTip(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.gproject.common.dto.proto.TipDTO.TipCode value = com.gproject.common.dto.proto.TipDTO.TipCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                code_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              msg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gproject.common.dto.proto.TipDTO.internal_static_gsp_GameTip_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gproject.common.dto.proto.TipDTO.internal_static_gsp_GameTip_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gproject.common.dto.proto.TipDTO.GameTip.class, com.gproject.common.dto.proto.TipDTO.GameTip.Builder.class);
    }

    public static com.google.protobuf.Parser<GameTip> PARSER =
        new com.google.protobuf.AbstractParser<GameTip>() {
      public GameTip parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameTip(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GameTip> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .gsp.TipCode code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private com.gproject.common.dto.proto.TipDTO.TipCode code_;
    /**
     * <code>optional .gsp.TipCode code = 1;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .gsp.TipCode code = 1;</code>
     */
    public com.gproject.common.dto.proto.TipDTO.TipCode getCode() {
      return code_;
    }

    // optional string msg = 2;
    public static final int MSG_FIELD_NUMBER = 2;
    private java.lang.Object msg_;
    /**
     * <code>optional string msg = 2;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      code_ = com.gproject.common.dto.proto.TipDTO.TipCode.UnKown;
      msg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, code_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, code_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gproject.common.dto.proto.TipDTO.GameTip parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.TipDTO.GameTip parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.TipDTO.GameTip parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gproject.common.dto.proto.TipDTO.GameTip parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.TipDTO.GameTip parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.TipDTO.GameTip parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.TipDTO.GameTip parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gproject.common.dto.proto.TipDTO.GameTip parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gproject.common.dto.proto.TipDTO.GameTip parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gproject.common.dto.proto.TipDTO.GameTip parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gproject.common.dto.proto.TipDTO.GameTip prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gsp.GameTip}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gproject.common.dto.proto.TipDTO.GameTipOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gproject.common.dto.proto.TipDTO.internal_static_gsp_GameTip_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gproject.common.dto.proto.TipDTO.internal_static_gsp_GameTip_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gproject.common.dto.proto.TipDTO.GameTip.class, com.gproject.common.dto.proto.TipDTO.GameTip.Builder.class);
      }

      // Construct using com.gproject.common.dto.proto.TipDTO.GameTip.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        code_ = com.gproject.common.dto.proto.TipDTO.TipCode.UnKown;
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gproject.common.dto.proto.TipDTO.internal_static_gsp_GameTip_descriptor;
      }

      public com.gproject.common.dto.proto.TipDTO.GameTip getDefaultInstanceForType() {
        return com.gproject.common.dto.proto.TipDTO.GameTip.getDefaultInstance();
      }

      public com.gproject.common.dto.proto.TipDTO.GameTip build() {
        com.gproject.common.dto.proto.TipDTO.GameTip result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gproject.common.dto.proto.TipDTO.GameTip buildPartial() {
        com.gproject.common.dto.proto.TipDTO.GameTip result = new com.gproject.common.dto.proto.TipDTO.GameTip(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gproject.common.dto.proto.TipDTO.GameTip) {
          return mergeFrom((com.gproject.common.dto.proto.TipDTO.GameTip)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gproject.common.dto.proto.TipDTO.GameTip other) {
        if (other == com.gproject.common.dto.proto.TipDTO.GameTip.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000002;
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gproject.common.dto.proto.TipDTO.GameTip parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gproject.common.dto.proto.TipDTO.GameTip) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .gsp.TipCode code = 1;
      private com.gproject.common.dto.proto.TipDTO.TipCode code_ = com.gproject.common.dto.proto.TipDTO.TipCode.UnKown;
      /**
       * <code>optional .gsp.TipCode code = 1;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .gsp.TipCode code = 1;</code>
       */
      public com.gproject.common.dto.proto.TipDTO.TipCode getCode() {
        return code_;
      }
      /**
       * <code>optional .gsp.TipCode code = 1;</code>
       */
      public Builder setCode(com.gproject.common.dto.proto.TipDTO.TipCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .gsp.TipCode code = 1;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = com.gproject.common.dto.proto.TipDTO.TipCode.UnKown;
        onChanged();
        return this;
      }

      // optional string msg = 2;
      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 2;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gsp.GameTip)
    }

    static {
      defaultInstance = new GameTip(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gsp.GameTip)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gsp_GameTip_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gsp_GameTip_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tTip.proto\022\003gsp\"2\n\007GameTip\022\032\n\004code\030\001 \001(" +
      "\0162\014.gsp.TipCode\022\013\n\003msg\030\002 \001(\t*\230\001\n\007TipCode" +
      "\022\n\n\006UnKown\020\001\022\010\n\004Fail\020\002\022\024\n\020PlayerInFighti" +
      "ng\020\003\022\017\n\013TokenExpire\020\004\022\014\n\010Uid_NULL\020\005\022\016\n\nT" +
      "oken_NULL\020\006\022\017\n\013Random_NULL\020\007\022\017\n\013Max_bag_" +
      "num\020\010\022\020\n\014Max_Item_num\020\tB\'\n\035com.gproject." +
      "common.dto.protoB\006TipDTO"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_gsp_GameTip_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_gsp_GameTip_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gsp_GameTip_descriptor,
              new java.lang.String[] { "Code", "Msg", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
